; HEADER_BLOCK_START
; generated by OrcaSlicer 1.6.3 on 2023-06-17 at 13:06:23
; total layer number: 1
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START
; thumbnail begin 300x300 2980
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAIgElEQVR4Ae3d3WueZx3A8RtqcdEtBr
; u6sbQ0ndmavsykzm7Zlrq01TjHYHUEHQMlvtVXtIN5MtSCFAZ60B0JnqwHO/DIFkFPdpKBJ55oEEEQ
; D/on9E+o/aF1MU3S5+V+ua77+nzge1gIPO3Dff96/a5UFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQoskPf2jqwAMT
; MxVAylbnptdu/PCFW3/79rmb35g/dLECSNGvzj1xNb6sNvfbLz21Hk9cFUAKjj34wMKfvvb8ja1fVn
; eKp62VRz9xvgLo0o+fmr200xfV1n52eu6Kpy2gdfFU9cdXn90Y9MvqTvFn4s9WAG2IYfqwX1RbXxEN
; 5IFGxevcb148eX2cL6utA3nHH4DaLU5/fDmejOr6sjKQBxoRw/K6v6gM5IFajTpYHzUDeWAk4w7Wxx
; 3Ie9oC7im+KGIY3sWX1eYM5IFd3dkDTKV42oqfqQLYbLs9wFSKn80rInDPPcBUioG84w9QsGH2AFN5
; Rbx4+2f2tAUFafu4Qt3FQN7xByhAV8cVmnjaso8IPRWvUSkP1sd52nL8AXokl8H6OE9bBvLQA23sAa
; aSfUTIVO6D9VGzjwiZ6ctgfdTsI0IG6r5gL/cM5CFRTV2wl3v2ESExJQ3WR80+InSs78cV6s4+InSk
; 9MH6qBnIQ4tSuWAv9wzkoWGpXbCXe/YRoSF93ANMpXja8ooINTBYbyf7iDCm3C7Y60P2EWFIpe4Bpp
; J9RBiQ4wppZCAPu7AHmGaOP8AW9gDTzj4i/Jc9wHyyj0ixHFfIsxjIxxNxBaUwWM87+4gUwR5gvzKQ
; p7fsAfYzxx/oHXuA/c8+ItkzWC+r+KztI5Ile4BlFq+I9hHJhj1ARfGKaB+RpDmuoM0ZyJOkePw3WN
; dOOf5AMgzWNUguCKRz9gA1bAbytM5gXePkgkBaY7CuOrKPSKNcsKcmMpCndjEsdcGemsoFgdTGYF1t
; 5YJARua4grooBvKOPzAUe4DqMgN5BhLDT8cVlEoG8uzIBXtKMfuI3MUeoFLPBYEYrCur7CMWzHEF5Z
; p9xILYA1Qfso9YAHuA6lOOP/SUPUD1OccfeiR+rbg9QPU9+4g9YLCu0rKPmCHHFVRy9hEzYrAuGcgn
; Lz6YGD7m9JdKajoD+QTZA5R2zj5iQuwBSoNlH7FDBuvS8NlH7IAL9qTxso/YAnuAUn3ZR2yQ4wpS/R
; nI18weoNR8jj/UIB5X7QFK7WQgPwZ7gFI3GcgPwWBd6j4D+QEYrEvpZB9xB/YApXQzkN/EHqCUfi4I
; rOwBSrlV5AWB9gClfCvqgsAffOaTl3L6cCTdXTEn5E8ffPD8n79+xmFQKeP++q2zt87O7F+rSnB46q
; MLb6/MX//X97+Q1Yck6YVbv/7iwvrD999X3hmt73z68JV/fPfzWX1YUqn983srty6cPHylKlk8bf3+
; y8/cyOmDk0rrvdeWbj6+7/7liv9487kjV70iSul1efn4esXdYiC//tXPGshLCRSD9aWD+9YqdhaviG
; +dOeFpS+qwt1c+tT51396ZisGsHp2+6PiD1G7xVPXK3PSliuHF09bvVhdv5PSBS7l2bXXx5szUR5Yr
; xhPHH7wiSs0UxxXeWHzsakV94mnLQF6qt3gFPLF/crmifhN790z9/PRRA3mphn557gmD9TbYR5RGL5
; 6qXpx92K/2apN9RGn4it0DTIV9ROne2QNMiH1Eaefev/2fVfYAE2QfUfr/YrBekS77iJI9wKwYyKvk
; DNYzFfuIf/nmWU9bKqIYrL96/IA9wJzZR1QJ/eErz9oD7JPXn541kFcv++nS3PWK/jm2f3LZQF59yR
; 5gAQ5MTizYR1TuuWCvMOePPOKCQGWXPcCCxUD+3ZdPbeT0F1bl9s5LT244roB9RCVdHFf40alZF+zx
; ARcEKsXsAbIrA3mlkj1ABuKCQHVZDNbPzuxfq2BQ9hHVRfYAGUsM5O0jqulisL42f8gFe4zPBYFqMn
; uANOInzzxuIK9au7x83GCd5sw/9DH7iBo7e4C0Jl4Rf/H8MU9bGil7gHQiLgh0/EGDFk9Vr8xNu2CP
; 7rggUIN0bXXRYJ102EfUdsVxhTcWH7MHSHrsI2pzBuskb2Lvnin7iIo9QIN1smEfscxcsEe27COWlT
; 1AesFAvt/FYP3CycP2AOkP+4j9zAV79Nqbzx0xkO9JLtijCDGQd/wh32KwvnRw31oFpTCQz7PYAzRY
; p1ixj+iCwPSLwbo9QKjsI6aeC/ZgG68/PWsgn1j2AGEX9hHTyB4gDOjA5MSCfcTucsEejGDl0YfW7C
; O2lz1AGFO8Ir778qmNnP7h59g7Lz254bgC1MQ+YjPZA4SG2EesN3uA0AL7iONnDxBaZB9xtOwBQkfs
; Iw6XC/YgATGQt4+4czFYX5s/ZLAOqbCPuH32ACFh9hE/6PLycYN1SN2x/ZPLJQ/k7QFCZkrdR7QHCB
; k7f+SRiyXsI8ZTlQv2oAf6PpC/trp403EF6Jm+7SPGcQUX7EGP9eWCQIN1KEjOA3l7gFCg2EfMaSDv
; gj0oXC77iPYAgf9JdSDvgj1gW6ldEPjea0su2AN2l8IFgfYAgYF1dUGgC/aAkcQr4ltnTrT2tGUPEB
; jb6tHpRvcR/37hc/YAgfo0tY/ogj2gMXH8oa5XRHuAQOPG3Ue0Bwi0amLvnqlR9hFjD9BgHejEoPuI
; 9gCBJNxrH9EeIJCcrfuI9gCBpN3ZR3z/9lDeHiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADCOfwPEAriVdQ17yAAA
; AABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=First_Layer_Square_0.2.stl_id_0_copy_0 CENTER=162.5,165 POLYGON=[[125,127.5],[200,127.5],[200,202.5],[125,202.5],[125,127.5]]
M73 P0 R2
;TYPE:Custom
START_PRINT T_BED=110 T_EXTRUDER=240
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode

    PRESSURE_ADVANCE_SELECT FILAMENT=ABS
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
M204 S1000
G1 E-.5 F3000
G1 X123.552 Y124.971 F9000
G1 Z.2
G1 E.5 F1800
;TYPE:Skirt
;WIDTH:0.5
G1 F3000
G1 X125 Y124.586 E.05272
G1 X200 Y124.586 E2.63954
M73 P1 R2
G1 X201.462 Y124.979 E.05327
G1 X202.529 Y126.052 E.05327
G1 X202.914 Y127.5 E.05272
G1 X202.914 Y202.5 E2.63954
M73 P2 R2
G1 X202.521 Y203.962 E.05327
G1 X201.448 Y205.029 E.05327
G1 X200 Y205.414 E.05272
G1 X125 Y205.414 E2.63954
M73 P3 R2
G1 X123.538 Y205.021 E.05327
G1 X122.471 Y203.948 E.05327
G1 X122.086 Y202.5 E.05272
G1 X122.086 Y127.5 E2.63954
M73 P4 R2
G1 X122.479 Y126.038 E.05327
G1 X123.51 Y125.013 E.05116
G1 X123.836 Y125.391 F9000
G1 F3000
G1 X123.985 Y125.262 E.00695
G1 X125 Y125.043 E.03653
G1 X200 Y125.043 E2.63954
M73 P5 R2
G1 X201.331 Y125.435 E.04884
G1 X202.238 Y126.485 E.04884
G1 X202.457 Y127.5 E.03653
G1 X202.457 Y202.5 E2.63954
M73 P6 R2
G1 X202.065 Y203.831 E.04884
G1 X201.015 Y204.738 E.04884
G1 X200 Y204.957 E.03653
G1 X125 Y204.957 E2.63954
M73 P7 R2
G1 X123.669 Y204.565 E.04884
G1 X122.762 Y203.515 E.04884
G1 X122.543 Y202.5 E.03653
G1 X122.543 Y127.5 E2.63954
M73 P8 R2
G1 X122.935 Y126.169 E.04884
G1 X123.791 Y125.43 E.03978
; printing object First_Layer_Square_0.2.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=First_Layer_Square_0.2.stl_id_0_copy_0
G1 E-.5
G1 X199.193 Y201.693 F9000
M73 P9 R2
G1 E.5 F1800
;TYPE:Inner wall
;WIDTH:0.499999
G1 F3000
G1 X125.807 Y201.693 E2.58273
M73 P10 R2
G1 X125.807 Y128.307 E2.58273
M73 P11 R2
G1 X199.193 Y128.307 E2.58273
M73 P12 R2
G1 X199.193 Y165 E1.29136
G1 X199.193 Y201.633 E1.28925
G1 X199.65 Y202.15 F9000
;TYPE:Outer wall
G1 F3000
G1 X125.35 Y202.15 E2.6149
M73 P13 R2
G1 X125.35 Y127.85 E2.6149
M73 P14 R2
G1 X199.65 Y127.85 E2.6149
M73 P15 R2
G1 X199.65 Y165 E1.30745
M73 P16 R2
G1 X199.65 Y202.09 E1.30534
G1 X199.581 Y202.11
G1 E-.5
G1 X198.13 Y128.444 F9000
M73 P17 R2
G1 E.5 F1800
;TYPE:Bottom surface
;WIDTH:0.500707
G1 F6300
G1 X198.85 Y129.164 E.03588
G1 X198.85 Y129.811 E.02282
G1 X197.689 Y128.65 E.0579
G1 X197.041 Y128.65 E.02282
G1 X198.85 Y130.459 E.09017
G1 X198.85 Y131.106 E.02282
G1 X196.394 Y128.65 E.12244
G1 X195.746 Y128.65 E.02282
G1 X198.85 Y131.754 E.15472
G1 X198.85 Y132.401 E.02282
G1 X195.099 Y128.65 E.18699
G1 X194.452 Y128.65 E.02282
G1 X198.85 Y133.048 E.21926
G1 X198.85 Y133.696 E.02282
G1 X193.804 Y128.65 E.25153
G1 X193.157 Y128.65 E.02282
G1 X198.85 Y134.343 E.28381
G1 X198.85 Y134.991 E.02282
G1 X192.509 Y128.65 E.31608
G1 X191.862 Y128.65 E.02282
M73 P18 R2
G1 X198.85 Y135.638 E.34835
G1 X198.85 Y136.285 E.02282
G1 X191.215 Y128.65 E.38062
G1 X190.567 Y128.65 E.02282
G1 X198.85 Y136.933 E.4129
G1 X198.85 Y137.58 E.02282
G1 X189.92 Y128.65 E.44517
G1 X189.272 Y128.65 E.02282
G1 X198.85 Y138.228 E.47744
G1 X198.85 Y138.875 E.02282
G1 X188.625 Y128.65 E.50971
G1 X187.977 Y128.65 E.02282
G1 X198.85 Y139.523 E.54199
M73 P19 R2
G1 X198.85 Y140.17 E.02282
G1 X187.33 Y128.65 E.57426
G1 X186.683 Y128.65 E.02282
G1 X198.85 Y140.817 E.60653
G1 X198.85 Y141.465 E.02282
G1 X186.035 Y128.65 E.6388
G1 X185.388 Y128.65 E.02282
G1 X198.85 Y142.112 E.67108
G1 X198.85 Y142.76 E.02282
G1 X184.74 Y128.65 E.70335
G1 X184.093 Y128.65 E.02282
G1 X198.85 Y143.407 E.73562
M73 P20 R2
G1 X198.85 Y144.054 E.02282
G1 X183.446 Y128.65 E.76789
G1 X182.798 Y128.65 E.02282
G1 X198.85 Y144.702 E.80017
G1 X198.85 Y145.349 E.02282
G1 X182.151 Y128.65 E.83244
G1 X181.503 Y128.65 E.02282
G1 X198.85 Y145.997 E.86471
G1 X198.85 Y146.644 E.02282
G1 X180.856 Y128.65 E.89698
M73 P21 R2
G1 X180.209 Y128.65 E.02282
G1 X198.85 Y147.291 E.92926
G1 X198.85 Y147.939 E.02282
G1 X179.561 Y128.65 E.96153
G1 X178.914 Y128.65 E.02282
G1 X198.85 Y148.586 E.9938
G1 X198.85 Y149.234 E.02282
G1 X178.266 Y128.65 E1.02607
M73 P22 R2
G1 X177.619 Y128.65 E.02282
G1 X198.85 Y149.881 E1.05835
G1 X198.85 Y150.528 E.02282
G1 X176.972 Y128.65 E1.09062
G1 X176.324 Y128.65 E.02282
G1 X198.85 Y151.176 E1.12289
G1 X198.85 Y151.823 E.02282
G1 X175.677 Y128.65 E1.15516
M73 P23 R2
G1 X175.029 Y128.65 E.02282
G1 X198.85 Y152.471 E1.18744
G1 X198.85 Y153.118 E.02282
G1 X174.382 Y128.65 E1.21971
G1 X173.734 Y128.65 E.02282
G1 X198.85 Y153.766 E1.25198
G1 X198.85 Y154.413 E.02282
G1 X173.087 Y128.65 E1.28425
M73 P24 R2
G1 X172.44 Y128.65 E.02282
G1 X198.85 Y155.06 E1.31653
G1 X198.85 Y155.708 E.02282
G1 X171.792 Y128.65 E1.3488
G1 X171.145 Y128.65 E.02282
G1 X198.85 Y156.355 E1.38107
M73 P25 R2
G1 X198.85 Y157.003 E.02282
G1 X170.497 Y128.65 E1.41334
G1 X169.85 Y128.65 E.02282
G1 X198.85 Y157.65 E1.44562
G1 X198.85 Y158.297 E.02282
G1 X169.203 Y128.65 E1.47789
M73 P26 R2
G1 X168.555 Y128.65 E.02282
G1 X198.85 Y158.945 E1.51016
G1 X198.85 Y159.592 E.02282
G1 X167.908 Y128.65 E1.54243
G1 X167.26 Y128.65 E.02282
G1 X198.85 Y160.24 E1.5747
M73 P27 R2
G1 X198.85 Y160.887 E.02282
G1 X166.613 Y128.65 E1.60698
G1 X165.966 Y128.65 E.02282
G1 X198.85 Y161.534 E1.63925
M73 P27 R1
G1 X198.85 Y162.182 E.02282
G1 X165.318 Y128.65 E1.67152
M73 P28 R1
G1 X164.671 Y128.65 E.02282
G1 X198.85 Y162.829 E1.70379
G1 X198.85 Y163.477 E.02282
G1 X164.023 Y128.65 E1.73607
G1 X163.376 Y128.65 E.02282
G1 X198.85 Y164.124 E1.76834
M73 P29 R1
G1 X198.85 Y164.771 E.02282
G1 X162.729 Y128.65 E1.80061
G1 X162.081 Y128.65 E.02282
G1 X198.85 Y165.419 E1.83288
G1 X198.85 Y166.066 E.02282
G1 X161.434 Y128.65 E1.86516
M73 P30 R1
G1 X160.786 Y128.65 E.02282
G1 X198.85 Y166.714 E1.89743
G1 X198.85 Y167.361 E.02282
G1 X160.139 Y128.65 E1.9297
G1 X159.492 Y128.65 E.02282
M73 P31 R1
G1 X198.85 Y168.008 E1.96197
G1 X198.85 Y168.656 E.02282
G1 X158.844 Y128.65 E1.99425
G1 X158.197 Y128.65 E.02282
G1 X198.85 Y169.303 E2.02652
M73 P32 R1
G1 X198.85 Y169.951 E.02282
G1 X157.549 Y128.65 E2.05879
G1 X156.902 Y128.65 E.02282
G1 X198.85 Y170.598 E2.09106
M73 P33 R1
G1 X198.85 Y171.246 E.02282
G1 X156.254 Y128.65 E2.12334
G1 X155.607 Y128.65 E.02282
G1 X198.85 Y171.893 E2.15561
G1 X198.85 Y172.54 E.02282
G1 X154.96 Y128.65 E2.18788
M73 P34 R1
G1 X154.312 Y128.65 E.02282
G1 X198.85 Y173.188 E2.22015
G1 X198.85 Y173.835 E.02282
G1 X153.665 Y128.65 E2.25243
M73 P35 R1
G1 X153.017 Y128.65 E.02282
G1 X198.85 Y174.483 E2.2847
G1 X198.85 Y175.13 E.02282
G1 X152.37 Y128.65 E2.31697
M73 P36 R1
G1 X151.723 Y128.65 E.02282
G1 X198.85 Y175.777 E2.34924
G1 X198.85 Y176.425 E.02282
G1 X151.075 Y128.65 E2.38152
M73 P37 R1
G1 X150.428 Y128.65 E.02282
G1 X198.85 Y177.072 E2.41379
G1 X198.85 Y177.72 E.02282
G1 X149.78 Y128.65 E2.44606
G1 X149.133 Y128.65 E.02282
G1 X198.85 Y178.367 E2.47833
M73 P38 R1
G1 X198.85 Y179.014 E.02282
G1 X148.486 Y128.65 E2.51061
G1 X147.838 Y128.65 E.02282
G1 X198.85 Y179.662 E2.54288
M73 P39 R1
G1 X198.85 Y180.309 E.02282
G1 X147.191 Y128.65 E2.57515
G1 X146.543 Y128.65 E.02282
G1 X198.85 Y180.957 E2.60742
M73 P40 R1
G1 X198.85 Y181.604 E.02282
G1 X145.896 Y128.65 E2.6397
G1 X145.249 Y128.65 E.02282
G1 X198.85 Y182.251 E2.67197
M73 P41 R1
G1 X198.85 Y182.899 E.02282
G1 X144.601 Y128.65 E2.70424
G1 X143.954 Y128.65 E.02282
G1 X198.85 Y183.546 E2.73651
M73 P42 R1
G1 X198.85 Y184.194 E.02282
G1 X143.306 Y128.65 E2.76879
G1 X142.659 Y128.65 E.02282
G1 X198.85 Y184.841 E2.80106
M73 P43 R1
G1 X198.85 Y185.489 E.02282
G1 X142.011 Y128.65 E2.83333
M73 P44 R1
G1 X141.364 Y128.65 E.02282
G1 X198.85 Y186.136 E2.8656
G1 X198.85 Y186.783 E.02282
G1 X140.717 Y128.65 E2.89788
M73 P45 R1
G1 X140.069 Y128.65 E.02282
G1 X198.85 Y187.431 E2.93015
G1 X198.85 Y188.078 E.02282
G1 X139.422 Y128.65 E2.96242
M73 P46 R1
G1 X138.774 Y128.65 E.02282
G1 X198.85 Y188.726 E2.99469
G1 X198.85 Y189.373 E.02282
G1 X138.127 Y128.65 E3.02697
M73 P47 R1
G1 X137.48 Y128.65 E.02282
G1 X198.85 Y190.02 E3.05924
G1 X198.85 Y190.668 E.02282
G1 X136.832 Y128.65 E3.09151
M73 P48 R1
G1 X136.185 Y128.65 E.02282
G1 X198.85 Y191.315 E3.12378
M73 P49 R1
G1 X198.85 Y191.963 E.02282
G1 X135.537 Y128.65 E3.15606
G1 X134.89 Y128.65 E.02282
G1 X198.85 Y192.61 E3.18833
M73 P50 R1
G1 X198.85 Y193.257 E.02282
G1 X134.243 Y128.65 E3.2206
G1 X133.595 Y128.65 E.02282
G1 X198.85 Y193.905 E3.25287
M73 P51 R1
G1 X198.85 Y194.552 E.02282
G1 X132.948 Y128.65 E3.28514
M73 P52 R1
G1 X132.3 Y128.65 E.02282
G1 X198.85 Y195.2 E3.31742
G1 X198.85 Y195.847 E.02282
G1 X131.653 Y128.65 E3.34969
M73 P53 R1
G1 X131.006 Y128.65 E.02282
G1 X198.85 Y196.494 E3.38196
G1 X198.85 Y197.142 E.02282
M73 P54 R1
G1 X130.358 Y128.65 E3.41423
G1 X129.711 Y128.65 E.02282
G1 X198.85 Y197.789 E3.44651
M73 P55 R1
G1 X198.85 Y198.437 E.02282
G1 X129.063 Y128.65 E3.47878
G1 X128.416 Y128.65 E.02282
G1 X198.85 Y199.084 E3.51105
M73 P56 R1
G1 X198.85 Y199.732 E.02282
G1 X127.768 Y128.65 E3.54332
M73 P57 R1
G1 X127.121 Y128.65 E.02282
G1 X198.85 Y200.379 E3.5756
G1 X198.85 Y201.026 E.02282
G1 X126.474 Y128.65 E3.60787
M73 P58 R1
G1 X126.15 Y128.65 E.01141
G1 X126.15 Y128.973 E.01141
G1 X198.527 Y201.35 E3.60788
M73 P59 R1
G1 X197.879 Y201.35 E.02282
G1 X126.15 Y129.621 E3.57561
G1 X126.15 Y130.268 E.02282
G1 X197.232 Y201.35 E3.54333
M73 P60 R1
G1 X196.584 Y201.35 E.02282
G1 X126.15 Y130.916 E3.51106
M73 P61 R1
G1 X126.15 Y131.563 E.02282
G1 X195.937 Y201.35 E3.47879
G1 X195.289 Y201.35 E.02282
G1 X126.15 Y132.211 E3.44652
M73 P62 R1
G1 X126.15 Y132.858 E.02282
G1 X194.642 Y201.35 E3.41424
M73 P63 R1
G1 X193.995 Y201.35 E.02282
G1 X126.15 Y133.505 E3.38197
G1 X126.15 Y134.153 E.02282
G1 X193.347 Y201.35 E3.3497
M73 P64 R0
G1 X192.7 Y201.35 E.02282
G1 X126.15 Y134.8 E3.31743
G1 X126.15 Y135.448 E.02282
G1 X192.052 Y201.35 E3.28515
M73 P65 R0
G1 X191.405 Y201.35 E.02282
G1 X126.15 Y136.095 E3.25288
M73 P66 R0
G1 X126.15 Y136.742 E.02282
G1 X190.758 Y201.35 E3.22061
G1 X190.11 Y201.35 E.02282
G1 X126.15 Y137.39 E3.18834
M73 P67 R0
G1 X126.15 Y138.037 E.02282
G1 X189.463 Y201.35 E3.15606
G1 X188.815 Y201.35 E.02282
G1 X126.15 Y138.685 E3.12379
M73 P68 R0
G1 X126.15 Y139.332 E.02282
G1 X188.168 Y201.35 E3.09152
M73 P69 R0
G1 X187.521 Y201.35 E.02282
G1 X126.15 Y139.979 E3.05925
G1 X126.15 Y140.627 E.02282
G1 X186.873 Y201.35 E3.02697
M73 P70 R0
G1 X186.226 Y201.35 E.02282
G1 X126.15 Y141.274 E2.9947
G1 X126.15 Y141.922 E.02282
G1 X185.578 Y201.35 E2.96243
M73 P71 R0
G1 X184.931 Y201.35 E.02282
G1 X126.15 Y142.569 E2.93016
G1 X126.15 Y143.216 E.02282
G1 X184.284 Y201.35 E2.89788
M73 P72 R0
G1 X183.636 Y201.35 E.02282
G1 X126.15 Y143.864 E2.86561
M73 P73 R0
G1 X126.15 Y144.511 E.02282
G1 X182.989 Y201.35 E2.83334
G1 X182.341 Y201.35 E.02282
G1 X126.15 Y145.159 E2.80107
M73 P74 R0
G1 X126.15 Y145.806 E.02282
G1 X181.694 Y201.35 E2.76879
G1 X181.046 Y201.35 E.02282
G1 X126.15 Y146.454 E2.73652
M73 P75 R0
G1 X126.15 Y147.101 E.02282
G1 X180.399 Y201.35 E2.70425
G1 X179.752 Y201.35 E.02282
G1 X126.15 Y147.748 E2.67198
M73 P76 R0
G1 X126.15 Y148.396 E.02282
G1 X179.104 Y201.35 E2.6397
G1 X178.457 Y201.35 E.02282
G1 X126.15 Y149.043 E2.60743
M73 P77 R0
G1 X126.15 Y149.691 E.02282
G1 X177.809 Y201.35 E2.57516
G1 X177.162 Y201.35 E.02282
G1 X126.15 Y150.338 E2.54289
M73 P78 R0
G1 X126.15 Y150.985 E.02282
G1 X176.515 Y201.35 E2.51061
G1 X175.867 Y201.35 E.02282
G1 X126.15 Y151.633 E2.47834
M73 P79 R0
G1 X126.15 Y152.28 E.02282
G1 X175.22 Y201.35 E2.44607
G1 X174.572 Y201.35 E.02282
G1 X126.15 Y152.928 E2.4138
M73 P80 R0
G1 X126.15 Y153.575 E.02282
G1 X173.925 Y201.35 E2.38152
G1 X173.278 Y201.35 E.02282
G1 X126.15 Y154.222 E2.34925
G1 X126.15 Y154.87 E.02282
G1 X172.63 Y201.35 E2.31698
M73 P81 R0
G1 X171.983 Y201.35 E.02282
G1 X126.15 Y155.517 E2.28471
G1 X126.15 Y156.165 E.02282
G1 X171.335 Y201.35 E2.25243
M73 P82 R0
G1 X170.688 Y201.35 E.02282
G1 X126.15 Y156.812 E2.22016
G1 X126.15 Y157.459 E.02282
G1 X170.041 Y201.35 E2.18789
M73 P83 R0
G1 X169.393 Y201.35 E.02282
G1 X126.15 Y158.107 E2.15562
G1 X126.15 Y158.754 E.02282
G1 X168.746 Y201.35 E2.12335
M73 P84 R0
G1 X168.098 Y201.35 E.02282
G1 X126.15 Y159.402 E2.09107
G1 X126.15 Y160.049 E.02282
G1 X167.451 Y201.35 E2.0588
G1 X166.803 Y201.35 E.02282
G1 X126.15 Y160.697 E2.02653
M73 P85 R0
G1 X126.15 Y161.344 E.02282
G1 X166.156 Y201.35 E1.99426
G1 X165.509 Y201.35 E.02282
G1 X126.15 Y161.991 E1.96198
M73 P86 R0
G1 X126.15 Y162.639 E.02282
G1 X164.861 Y201.35 E1.92971
G1 X164.214 Y201.35 E.02282
G1 X126.15 Y163.286 E1.89744
G1 X126.15 Y163.934 E.02282
G1 X163.566 Y201.35 E1.86517
M73 P87 R0
G1 X162.919 Y201.35 E.02282
G1 X126.15 Y164.581 E1.83289
G1 X126.15 Y165.228 E.02282
G1 X162.272 Y201.35 E1.80062
G1 X161.624 Y201.35 E.02282
G1 X126.15 Y165.876 E1.76835
M73 P88 R0
G1 X126.15 Y166.523 E.02282
G1 X160.977 Y201.35 E1.73608
G1 X160.329 Y201.35 E.02282
G1 X126.15 Y167.171 E1.7038
M73 P89 R0
G1 X126.15 Y167.818 E.02282
G1 X159.682 Y201.35 E1.67153
G1 X159.035 Y201.35 E.02282
G1 X126.15 Y168.465 E1.63926
G1 X126.15 Y169.113 E.02282
G1 X158.387 Y201.35 E1.60699
M73 P90 R0
G1 X157.74 Y201.35 E.02282
G1 X126.15 Y169.76 E1.57471
G1 X126.15 Y170.408 E.02282
G1 X157.092 Y201.35 E1.54244
G1 X156.445 Y201.35 E.02282
G1 X126.15 Y171.055 E1.51017
M73 P91 R0
G1 X126.15 Y171.702 E.02282
G1 X155.798 Y201.35 E1.4779
G1 X155.15 Y201.35 E.02282
G1 X126.15 Y172.35 E1.44562
G1 X126.15 Y172.997 E.02282
G1 X154.503 Y201.35 E1.41335
G1 X153.855 Y201.35 E.02282
G1 X126.15 Y173.645 E1.38108
M73 P92 R0
G1 X126.15 Y174.292 E.02282
G1 X153.208 Y201.35 E1.34881
G1 X152.56 Y201.35 E.02282
G1 X126.15 Y174.94 E1.31653
G1 X126.15 Y175.587 E.02282
G1 X151.913 Y201.35 E1.28426
M73 P93 R0
G1 X151.266 Y201.35 E.02282
G1 X126.15 Y176.234 E1.25199
G1 X126.15 Y176.882 E.02282
G1 X150.618 Y201.35 E1.21972
G1 X149.971 Y201.35 E.02282
G1 X126.15 Y177.529 E1.18744
G1 X126.15 Y178.177 E.02282
G1 X149.323 Y201.35 E1.15517
M73 P94 R0
G1 X148.676 Y201.35 E.02282
G1 X126.15 Y178.824 E1.1229
G1 X126.15 Y179.471 E.02282
G1 X148.029 Y201.35 E1.09063
G1 X147.381 Y201.35 E.02282
G1 X126.15 Y180.119 E1.05835
G1 X126.15 Y180.766 E.02282
G1 X146.734 Y201.35 E1.02608
M73 P95 R0
G1 X146.086 Y201.35 E.02282
G1 X126.15 Y181.414 E.99381
G1 X126.15 Y182.061 E.02282
G1 X145.439 Y201.35 E.96154
G1 X144.792 Y201.35 E.02282
G1 X126.15 Y182.708 E.92926
G1 X126.15 Y183.356 E.02282
G1 X144.144 Y201.35 E.89699
M73 P96 R0
G1 X143.497 Y201.35 E.02282
G1 X126.15 Y184.003 E.86472
G1 X126.15 Y184.651 E.02282
G1 X142.849 Y201.35 E.83245
G1 X142.202 Y201.35 E.02282
G1 X126.15 Y185.298 E.80017
G1 X126.15 Y185.945 E.02282
G1 X141.555 Y201.35 E.7679
G1 X140.907 Y201.35 E.02282
G1 X126.15 Y186.593 E.73563
M73 P97 R0
G1 X126.15 Y187.24 E.02282
G1 X140.26 Y201.35 E.70336
G1 X139.612 Y201.35 E.02282
G1 X126.15 Y187.888 E.67108
G1 X126.15 Y188.535 E.02282
G1 X138.965 Y201.35 E.63881
G1 X138.318 Y201.35 E.02282
G1 X126.15 Y189.182 E.60654
G1 X126.15 Y189.83 E.02282
G1 X137.67 Y201.35 E.57427
M73 P98 R0
G1 X137.023 Y201.35 E.02282
G1 X126.15 Y190.477 E.542
G1 X126.15 Y191.125 E.02282
G1 X136.375 Y201.35 E.50972
G1 X135.728 Y201.35 E.02282
G1 X126.15 Y191.772 E.47745
G1 X126.15 Y192.42 E.02282
G1 X135.08 Y201.35 E.44518
G1 X134.433 Y201.35 E.02282
G1 X126.15 Y193.067 E.41291
G1 X126.15 Y193.714 E.02282
G1 X133.786 Y201.35 E.38063
G1 X133.138 Y201.35 E.02282
G1 X126.15 Y194.362 E.34836
M73 P99 R0
G1 X126.15 Y195.009 E.02282
G1 X132.491 Y201.35 E.31609
G1 X131.843 Y201.35 E.02282
G1 X126.15 Y195.657 E.28382
G1 X126.15 Y196.304 E.02282
G1 X131.196 Y201.35 E.25154
G1 X130.549 Y201.35 E.02282
G1 X126.15 Y196.951 E.21927
G1 X126.15 Y197.599 E.02282
G1 X129.901 Y201.35 E.187
G1 X129.254 Y201.35 E.02282
G1 X126.15 Y198.246 E.15473
G1 X126.15 Y198.894 E.02282
G1 X128.606 Y201.35 E.12245
G1 X127.959 Y201.35 E.02282
G1 X126.15 Y199.541 E.09018
G1 X126.15 Y200.188 E.02282
G1 X127.312 Y201.35 E.05791
G1 X126.664 Y201.35 E.02282
G1 X125.944 Y200.63 E.03589
; stop printing object First_Layer_Square_0.2.stl id:0 copy 0
EXCLUDE_OBJECT_END NAME=First_Layer_Square_0.2.stl_id_0_copy_0
G1 E-.5 F3000
M106 S0
;TYPE:Custom
; filament end gcode 
END_PRINT
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 454.63
; filament used [cm3] = 1.09
; filament used [g] = 1.14
; filament cost = 0.02; total filament used [g] = 1.14
; total filament cost = 0.02
; total layers count = 1
; estimated printing time (normal mode) = 2m 45s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; additional_cooling_fan_speed = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_temperature_difference = 10
; before_layer_change_gcode = 
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 100%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 50
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 5
; chamber_temperature = 0
; change_filament_gcode = 
; close_fan_the_first_x_layers = 3
; cool_plate_temp = 105
; cool_plate_temp_initial_layer = 105
; curr_bed_type = High Temp Plate
; default_acceleration = 7000
; default_filament_colour = ""
; default_filament_profile = 
; default_jerk = 0
; default_print_profile = 0.16mm Optimal @Bambu Lab X1 Carbon 0.4 nozzle
; deretraction_speed = 0
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = bridge_acceleration;brim_type;elefant_foot_compensation;filename_format;initial_layer_acceleration;inner_wall_acceleration;outer_wall_acceleration;reduce_crossing_wall;skirt_loops;top_shell_layers;travel_acceleration;travel_speed;filament_deretraction_speed;filament_retraction_length;filament_retraction_speed;filament_start_gcode;hot_plate_temp;hot_plate_temp_initial_layer;nozzle_temperature;nozzle_temperature_initial_layer;deretraction_speed;gcode_flavor;machine_end_gcode;machine_max_acceleration_extruding;machine_max_acceleration_x;machine_max_acceleration_y;machine_max_jerk_e;machine_max_jerk_x;machine_max_jerk_y;machine_max_jerk_z;machine_start_gcode;print_host;printable_area;retract_when_changing_layer;retraction_length;wipe
; draft_shield = disabled
; elefant_foot_compensation = 0.1
; enable_arc_fitting = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 105
; eng_plate_temp_initial_layer = 105
; ensure_vertical_shell_thickness = 1
; exclude_object = 1
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 30
; fan_kickstart = 0
; fan_max_speed = 80
; fan_min_speed = 10
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #F2754E
; filament_cost = 20
; filament_density = 1.04
; filament_deretraction_speed = 30
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.926
; filament_ids = GFB99
; filament_is_support = 0
; filament_max_volumetric_speed = 12
; filament_minimal_purge_on_wipe_tower = 15
; filament_retraction_length = 0.5
; filament_retraction_speed = 50
; filament_settings_id = ABS
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; Filament gcode\n{if nozzle_diameter[0] == 0.2}\n     PRESSURE_ADVANCE_SELECT Nozzle=0.2 FILAMENT=ABS\n{ else }\n    PRESSURE_ADVANCE_SELECT FILAMENT=ABS\n{ endif }"
; filament_type = ABS
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_infill_speed = 100
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; host_type = octoprint
; hot_plate_temp = 110
; hot_plate_temp_initial_layer = 110
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @Tronxy";"Tronxy Generic ABS";"Tronxy X5SA 400 0.4 nozzle"
; initial_layer_acceleration = 1000
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 200
; interface_shells = 0
; internal_bridge_support_thickness = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.4
; internal_solid_infill_speed = 200
; ironing_flow = 10%
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.4
; machine_end_gcode = END_PRINT
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 6000
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 6000
; machine_max_acceleration_y = 6000
; machine_max_acceleration_z = 100
; machine_max_jerk_e = 2.5
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 0.3
; machine_max_speed_e = 60
; machine_max_speed_x = 500
; machine_max_speed_y = 500
; machine_max_speed_z = 10
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = 
; machine_start_gcode = START_PRINT T_BED=[first_layer_bed_temperature] T_EXTRUDER=[first_layer_temperature]
; machine_unload_filament_time = 0
; max_bridge_length = 10
; max_layer_height = 0.28
; max_travel_detour_distance = 0
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; minimum_sparse_infill_area = 15
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 240
; nozzle_temperature_initial_layer = 240
; nozzle_temperature_range_high = 270
; nozzle_temperature_range_low = 240
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; outer_wall_acceleration = 4000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.4
; outer_wall_speed = 120
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 80
; overhang_fan_threshold = 25%
; overhang_speed_classic = 0
; post_process = 
; precise_outer_wall = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Tronxy X5SA 400 0.4 nozzle"
; print_flow_ratio = 1
; print_host = 192.168.6.5:7126
; print_host_webui = 
; print_sequence = by layer
; print_settings_id = 0.20mm @Tronxy
; printable_area = 0x0,325x0,325x330,0x330
; printable_height = 400
; printer_model = Tronxy X5SA 400 Marlin Firmware
; printer_settings_id = TronXY X5SA
; printer_technology = FFF
; printer_variant = 0.4
; printhost_apikey = 
; printhost_authorization_type = key
; printhost_cafile = 
; printhost_password = 
; printhost_port = 
; printhost_ssl_ignore_revoke = 0
; printhost_user = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 1
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 1
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 0
; retraction_length = 0.8
; retraction_minimum_travel = 2
; retraction_speed = 60
; role_based_wipe_speed = 1
; scan_first_layer = 0
; seam_gap = 15%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 2
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 3
; slow_down_layers = 0
; slow_down_min_speed = 10
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 200
; spiral_mode = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_pattern = rectilinear
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.4
; support_material_interface_fan_speed = -1
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 110
; template_custom_gcode = 
; textured_plate_temp = 105
; textured_plate_temp_initial_layer = 105
; thick_bridges = 0
; thumbnails = 300x300
; timelapse_type = 0
; top_shell_layers = 3
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 3000
; top_surface_jerk = 9
; top_surface_line_width = 0.4
; top_surface_pattern = monotonic
; top_surface_speed = 100
; travel_acceleration = 9000
; travel_jerk = 12
; travel_speed = 150
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_diameter = 5
; tree_support_branch_distance = 5
; tree_support_brim_width = 3
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_infill_order = inner wall/outer wall/infill
; wall_loops = 2
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_distance = 2
; wipe_on_loops = 1
; wipe_speed = 80%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 155.000
; wipe_tower_y = 220.000
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0
; z_hop_types = Normal Lift
; first_layer_bed_temperature = 110
; bed_shape = 0x0,325x0,325x330,0x330
; first_layer_temperature = 240
; first_layer_height = 0.200
; CONFIG_BLOCK_END


