; HEADER_BLOCK_START
; generated by OrcaSlicer 1.6.3 on 2023-06-17 at 18:38:51
; total layer number: 1
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START
; thumbnail begin 300x300 2980
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAIgElEQVR4Ae3d3WueZx3A8RtqcdEtBr
; u6sbQ0ndmavsykzm7Zlrq01TjHYHUEHQMlvtVXtIN5MtSCFAZ60B0JnqwHO/DIFkFPdpKBJ55oEEEQ
; D/on9E+o/aF1MU3S5+V+ua77+nzge1gIPO3Dff96/a5UFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQoskPf2jqwAMT
; MxVAylbnptdu/PCFW3/79rmb35g/dLECSNGvzj1xNb6sNvfbLz21Hk9cFUAKjj34wMKfvvb8ja1fVn
; eKp62VRz9xvgLo0o+fmr200xfV1n52eu6Kpy2gdfFU9cdXn90Y9MvqTvFn4s9WAG2IYfqwX1RbXxEN
; 5IFGxevcb148eX2cL6utA3nHH4DaLU5/fDmejOr6sjKQBxoRw/K6v6gM5IFajTpYHzUDeWAk4w7Wxx
; 3Ie9oC7im+KGIY3sWX1eYM5IFd3dkDTKV42oqfqQLYbLs9wFSKn80rInDPPcBUioG84w9QsGH2AFN5
; Rbx4+2f2tAUFafu4Qt3FQN7xByhAV8cVmnjaso8IPRWvUSkP1sd52nL8AXokl8H6OE9bBvLQA23sAa
; aSfUTIVO6D9VGzjwiZ6ctgfdTsI0IG6r5gL/cM5CFRTV2wl3v2ESExJQ3WR80+InSs78cV6s4+InSk
; 9MH6qBnIQ4tSuWAv9wzkoWGpXbCXe/YRoSF93ANMpXja8ooINTBYbyf7iDCm3C7Y60P2EWFIpe4Bpp
; J9RBiQ4wppZCAPu7AHmGaOP8AW9gDTzj4i/Jc9wHyyj0ixHFfIsxjIxxNxBaUwWM87+4gUwR5gvzKQ
; p7fsAfYzxx/oHXuA/c8+ItkzWC+r+KztI5Ile4BlFq+I9hHJhj1ARfGKaB+RpDmuoM0ZyJOkePw3WN
; dOOf5AMgzWNUguCKRz9gA1bAbytM5gXePkgkBaY7CuOrKPSKNcsKcmMpCndjEsdcGemsoFgdTGYF1t
; 5YJARua4grooBvKOPzAUe4DqMgN5BhLDT8cVlEoG8uzIBXtKMfuI3MUeoFLPBYEYrCur7CMWzHEF5Z
; p9xILYA1Qfso9YAHuA6lOOP/SUPUD1OccfeiR+rbg9QPU9+4g9YLCu0rKPmCHHFVRy9hEzYrAuGcgn
; Lz6YGD7m9JdKajoD+QTZA5R2zj5iQuwBSoNlH7FDBuvS8NlH7IAL9qTxso/YAnuAUn3ZR2yQ4wpS/R
; nI18weoNR8jj/UIB5X7QFK7WQgPwZ7gFI3GcgPwWBd6j4D+QEYrEvpZB9xB/YApXQzkN/EHqCUfi4I
; rOwBSrlV5AWB9gClfCvqgsAffOaTl3L6cCTdXTEn5E8ffPD8n79+xmFQKeP++q2zt87O7F+rSnB46q
; MLb6/MX//X97+Q1Yck6YVbv/7iwvrD999X3hmt73z68JV/fPfzWX1YUqn983srty6cPHylKlk8bf3+
; y8/cyOmDk0rrvdeWbj6+7/7liv9487kjV70iSul1efn4esXdYiC//tXPGshLCRSD9aWD+9YqdhaviG
; +dOeFpS+qwt1c+tT51396ZisGsHp2+6PiD1G7xVPXK3PSliuHF09bvVhdv5PSBS7l2bXXx5szUR5Yr
; xhPHH7wiSs0UxxXeWHzsakV94mnLQF6qt3gFPLF/crmifhN790z9/PRRA3mphn557gmD9TbYR5RGL5
; 6qXpx92K/2apN9RGn4it0DTIV9ROne2QNMiH1Eaefev/2fVfYAE2QfUfr/YrBekS77iJI9wKwYyKvk
; DNYzFfuIf/nmWU9bKqIYrL96/IA9wJzZR1QJ/eErz9oD7JPXn541kFcv++nS3PWK/jm2f3LZQF59yR
; 5gAQ5MTizYR1TuuWCvMOePPOKCQGWXPcCCxUD+3ZdPbeT0F1bl9s5LT244roB9RCVdHFf40alZF+zx
; ARcEKsXsAbIrA3mlkj1ABuKCQHVZDNbPzuxfq2BQ9hHVRfYAGUsM5O0jqulisL42f8gFe4zPBYFqMn
; uANOInzzxuIK9au7x83GCd5sw/9DH7iBo7e4C0Jl4Rf/H8MU9bGil7gHQiLgh0/EGDFk9Vr8xNu2CP
; 7rggUIN0bXXRYJ102EfUdsVxhTcWH7MHSHrsI2pzBuskb2Lvnin7iIo9QIN1smEfscxcsEe27COWlT
; 1AesFAvt/FYP3CycP2AOkP+4j9zAV79Nqbzx0xkO9JLtijCDGQd/wh32KwvnRw31oFpTCQz7PYAzRY
; p1ixj+iCwPSLwbo9QKjsI6aeC/ZgG68/PWsgn1j2AGEX9hHTyB4gDOjA5MSCfcTucsEejGDl0YfW7C
; O2lz1AGFO8Ir778qmNnP7h59g7Lz254bgC1MQ+YjPZA4SG2EesN3uA0AL7iONnDxBaZB9xtOwBQkfs
; Iw6XC/YgATGQt4+4czFYX5s/ZLAOqbCPuH32ACFh9hE/6PLycYN1SN2x/ZPLJQ/k7QFCZkrdR7QHCB
; k7f+SRiyXsI8ZTlQv2oAf6PpC/trp403EF6Jm+7SPGcQUX7EGP9eWCQIN1KEjOA3l7gFCg2EfMaSDv
; gj0oXC77iPYAgf9JdSDvgj1gW6ldEPjea0su2AN2l8IFgfYAgYF1dUGgC/aAkcQr4ltnTrT2tGUPEB
; jb6tHpRvcR/37hc/YAgfo0tY/ogj2gMXH8oa5XRHuAQOPG3Ue0Bwi0amLvnqlR9hFjD9BgHejEoPuI
; 9gCBJNxrH9EeIJCcrfuI9gCBpN3ZR3z/9lDeHiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADCOfwPEAriVdQ17yAAA
; AABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=First_Layer_Square_0.2.stl_id_0_copy_0 CENTER=170,171 POLYGON=[[132.5,133.5],[207.5,133.5],[207.5,208.5],[132.5,208.5],[132.5,133.5]]
M73 P0 R2
;TYPE:Custom
START_PRINT T_BED=60 T_EXTRUDER=200
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode

    PRESSURE_ADVANCE_SELECT FILAMENT=PLA
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
M204 S1000
G1 E-.5 F3600
G1 X130.645 Y131.376 F9000
G1 Z.2
G1 E.5 F3600
;TYPE:Skirt
;WIDTH:0.5
G1 F3000
G1 X131.052 Y130.971 E.02139
G1 X132.5 Y130.586 E.0558
G1 X207.5 Y130.586 E2.79346
M73 P1 R2
G1 X208.962 Y130.979 E.05638
G1 X210.029 Y132.052 E.05638
G1 X210.414 Y133.5 E.0558
G1 X210.414 Y208.5 E2.79346
M73 P2 R2
G1 X210.021 Y209.962 E.05638
G1 X208.948 Y211.029 E.05638
G1 X207.5 Y211.414 E.0558
G1 X132.5 Y211.414 E2.79346
M73 P3 R2
G1 X131.038 Y211.021 E.05638
G1 X129.971 Y209.948 E.05638
G1 X129.586 Y208.5 E.0558
G1 X129.586 Y133.5 E2.79346
M73 P4 R2
G1 X129.979 Y132.038 E.05638
G1 X130.602 Y131.418 E.03275
G1 X130.902 Y131.765 F9000
G1 F3000
G1 X131.485 Y131.262 E.02869
G1 X132.5 Y131.043 E.03866
G1 X207.5 Y131.043 E2.79346
M73 P5 R2
G1 X208.831 Y131.435 E.05169
G1 X209.738 Y132.485 E.05169
G1 X209.957 Y133.5 E.03866
G1 X209.957 Y208.5 E2.79346
M73 P6 R2
G1 X209.565 Y209.831 E.05169
G1 X208.515 Y210.738 E.05169
G1 X207.5 Y210.957 E.03866
G1 X132.5 Y210.957 E2.79346
M73 P7 R2
G1 X131.169 Y210.565 E.05169
G1 X130.262 Y209.515 E.05169
G1 X130.043 Y208.5 E.03866
G1 X130.043 Y133.5 E2.79346
M73 P8 R2
G1 X130.435 Y132.169 E.05169
G1 X130.857 Y131.805 E.02076
; printing object First_Layer_Square_0.2.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=First_Layer_Square_0.2.stl_id_0_copy_0
G1 E-.5 F3600
G1 X206.693 Y207.693 F9000
M73 P9 R2
G1 E.5 F3600
;TYPE:Inner wall
;WIDTH:0.499999
G1 F3000
G1 X133.307 Y207.693 E2.73334
M73 P10 R2
G1 X133.307 Y134.307 E2.73334
M73 P11 R2
G1 X206.693 Y134.307 E2.73334
M73 P12 R2
G1 X206.693 Y171 E1.36667
G1 X206.693 Y207.633 E1.36444
M73 P13 R2
G1 X207.15 Y208.15 F9000
;TYPE:Outer wall
G1 F3000
G1 X132.85 Y208.15 E2.76739
G1 X132.85 Y133.85 E2.76739
M73 P14 R2
G1 X207.15 Y133.85 E2.76739
M73 P15 R2
G1 X207.15 Y171 E1.38369
M73 P16 R2
G1 X207.15 Y208.09 E1.38146
G1 X207.081 Y208.11
G1 E-.5 F3600
G1 X205.63 Y134.444 F9000
M73 P17 R2
G1 E.5 F3600
;TYPE:Bottom surface
;WIDTH:0.500707
G1 F6300
G1 X206.35 Y135.164 E.03797
G1 X206.35 Y135.811 E.02415
G1 X205.189 Y134.65 E.06128
G1 X204.541 Y134.65 E.02415
G1 X206.35 Y136.459 E.09543
G1 X206.35 Y137.106 E.02415
G1 X203.894 Y134.65 E.12959
G1 X203.246 Y134.65 E.02415
G1 X206.35 Y137.754 E.16374
G1 X206.35 Y138.401 E.02415
G1 X202.599 Y134.65 E.19789
G1 X201.952 Y134.65 E.02415
G1 X206.35 Y139.048 E.23205
G1 X206.35 Y139.696 E.02415
G1 X201.304 Y134.65 E.2662
G1 X200.657 Y134.65 E.02415
G1 X206.35 Y140.343 E.30036
G1 X206.35 Y140.991 E.02415
G1 X200.009 Y134.65 E.33451
M73 P18 R2
G1 X199.362 Y134.65 E.02415
G1 X206.35 Y141.638 E.36867
G1 X206.35 Y142.285 E.02415
G1 X198.715 Y134.65 E.40282
G1 X198.067 Y134.65 E.02415
G1 X206.35 Y142.933 E.43697
G1 X206.35 Y143.58 E.02415
G1 X197.42 Y134.65 E.47113
G1 X196.772 Y134.65 E.02415
G1 X206.35 Y144.228 E.50528
G1 X206.35 Y144.875 E.02415
G1 X196.125 Y134.65 E.53944
G1 X195.477 Y134.65 E.02415
G1 X206.35 Y145.523 E.57359
M73 P19 R2
G1 X206.35 Y146.17 E.02415
G1 X194.83 Y134.65 E.60775
G1 X194.183 Y134.65 E.02415
G1 X206.35 Y146.817 E.6419
G1 X206.35 Y147.465 E.02415
G1 X193.535 Y134.65 E.67606
G1 X192.888 Y134.65 E.02415
G1 X206.35 Y148.112 E.71021
G1 X206.35 Y148.76 E.02415
G1 X192.24 Y134.65 E.74436
G1 X191.593 Y134.65 E.02415
G1 X206.35 Y149.407 E.77852
M73 P20 R2
G1 X206.35 Y150.054 E.02415
G1 X190.946 Y134.65 E.81267
G1 X190.298 Y134.65 E.02415
G1 X206.35 Y150.702 E.84683
G1 X206.35 Y151.349 E.02415
G1 X189.651 Y134.65 E.88098
G1 X189.003 Y134.65 E.02415
G1 X206.35 Y151.997 E.91514
G1 X206.35 Y152.644 E.02415
G1 X188.356 Y134.65 E.94929
M73 P21 R2
G1 X187.709 Y134.65 E.02415
G1 X206.35 Y153.291 E.98345
G1 X206.35 Y153.939 E.02415
G1 X187.061 Y134.65 E1.0176
G1 X186.414 Y134.65 E.02415
G1 X206.35 Y154.586 E1.05175
G1 X206.35 Y155.234 E.02415
G1 X185.766 Y134.65 E1.08591
M73 P22 R2
G1 X185.119 Y134.65 E.02415
G1 X206.35 Y155.881 E1.12006
G1 X206.35 Y156.528 E.02415
G1 X184.472 Y134.65 E1.15422
G1 X183.824 Y134.65 E.02415
G1 X206.35 Y157.176 E1.18837
G1 X206.35 Y157.823 E.02415
G1 X183.177 Y134.65 E1.22253
M73 P23 R2
G1 X182.529 Y134.65 E.02415
G1 X206.35 Y158.471 E1.25668
G1 X206.35 Y159.118 E.02415
G1 X181.882 Y134.65 E1.29084
G1 X181.234 Y134.65 E.02415
G1 X206.35 Y159.766 E1.32499
G1 X206.35 Y160.413 E.02415
G1 X180.587 Y134.65 E1.35914
M73 P24 R2
G1 X179.94 Y134.65 E.02415
G1 X206.35 Y161.06 E1.3933
G1 X206.35 Y161.708 E.02415
G1 X179.292 Y134.65 E1.42745
G1 X178.645 Y134.65 E.02415
G1 X206.35 Y162.355 E1.46161
M73 P25 R2
G1 X206.35 Y163.003 E.02415
G1 X177.997 Y134.65 E1.49576
G1 X177.35 Y134.65 E.02415
G1 X206.35 Y163.65 E1.52992
G1 X206.35 Y164.297 E.02415
G1 X176.703 Y134.65 E1.56407
M73 P26 R2
G1 X176.055 Y134.65 E.02415
G1 X206.35 Y164.945 E1.59823
G1 X206.35 Y165.592 E.02415
G1 X175.408 Y134.65 E1.63238
G1 X174.76 Y134.65 E.02415
G1 X206.35 Y166.24 E1.66653
M73 P27 R2
G1 X206.35 Y166.887 E.02415
G1 X174.113 Y134.65 E1.70069
G1 X173.466 Y134.65 E.02415
G1 X206.35 Y167.534 E1.73484
M73 P27 R1
G1 X206.35 Y168.182 E.02415
G1 X172.818 Y134.65 E1.769
M73 P28 R1
G1 X172.171 Y134.65 E.02415
G1 X206.35 Y168.829 E1.80315
G1 X206.35 Y169.477 E.02415
G1 X171.523 Y134.65 E1.83731
G1 X170.876 Y134.65 E.02415
G1 X206.35 Y170.124 E1.87146
M73 P29 R1
G1 X206.35 Y170.771 E.02415
G1 X170.229 Y134.65 E1.90562
G1 X169.581 Y134.65 E.02415
G1 X206.35 Y171.419 E1.93977
G1 X206.35 Y172.066 E.02415
G1 X168.934 Y134.65 E1.97392
M73 P30 R1
G1 X168.286 Y134.65 E.02415
G1 X206.35 Y172.714 E2.00808
G1 X206.35 Y173.361 E.02415
G1 X167.639 Y134.65 E2.04223
M73 P31 R1
G1 X166.992 Y134.65 E.02415
G1 X206.35 Y174.008 E2.07639
G1 X206.35 Y174.656 E.02415
G1 X166.344 Y134.65 E2.11054
G1 X165.697 Y134.65 E.02415
G1 X206.35 Y175.303 E2.1447
M73 P32 R1
G1 X206.35 Y175.951 E.02415
G1 X165.049 Y134.65 E2.17885
G1 X164.402 Y134.65 E.02415
G1 X206.35 Y176.598 E2.21301
M73 P33 R1
G1 X206.35 Y177.246 E.02415
G1 X163.754 Y134.65 E2.24716
G1 X163.107 Y134.65 E.02415
G1 X206.35 Y177.893 E2.28131
G1 X206.35 Y178.54 E.02415
G1 X162.46 Y134.65 E2.31547
M73 P34 R1
G1 X161.812 Y134.65 E.02415
G1 X206.35 Y179.188 E2.34962
G1 X206.35 Y179.835 E.02415
G1 X161.165 Y134.65 E2.38378
M73 P35 R1
G1 X160.517 Y134.65 E.02415
G1 X206.35 Y180.483 E2.41793
G1 X206.35 Y181.13 E.02415
G1 X159.87 Y134.65 E2.45209
M73 P36 R1
G1 X159.223 Y134.65 E.02415
G1 X206.35 Y181.777 E2.48624
G1 X206.35 Y182.425 E.02415
G1 X158.575 Y134.65 E2.5204
M73 P37 R1
G1 X157.928 Y134.65 E.02415
G1 X206.35 Y183.072 E2.55455
G1 X206.35 Y183.72 E.02415
G1 X157.28 Y134.65 E2.5887
G1 X156.633 Y134.65 E.02415
G1 X206.35 Y184.367 E2.62286
M73 P38 R1
G1 X206.35 Y185.014 E.02415
G1 X155.986 Y134.65 E2.65701
G1 X155.338 Y134.65 E.02415
G1 X206.35 Y185.662 E2.69117
M73 P39 R1
G1 X206.35 Y186.309 E.02415
G1 X154.691 Y134.65 E2.72532
G1 X154.043 Y134.65 E.02415
G1 X206.35 Y186.957 E2.75948
M73 P40 R1
G1 X206.35 Y187.604 E.02415
G1 X153.396 Y134.65 E2.79363
G1 X152.749 Y134.65 E.02415
G1 X206.35 Y188.251 E2.82778
M73 P41 R1
G1 X206.35 Y188.899 E.02415
G1 X152.101 Y134.65 E2.86194
G1 X151.454 Y134.65 E.02415
G1 X206.35 Y189.546 E2.89609
M73 P42 R1
G1 X206.35 Y190.194 E.02415
G1 X150.806 Y134.65 E2.93025
G1 X150.159 Y134.65 E.02415
M73 P43 R1
G1 X206.35 Y190.841 E2.9644
G1 X206.35 Y191.489 E.02415
G1 X149.511 Y134.65 E2.99856
M73 P44 R1
G1 X148.864 Y134.65 E.02415
G1 X206.35 Y192.136 E3.03271
G1 X206.35 Y192.783 E.02415
G1 X148.217 Y134.65 E3.06687
M73 P45 R1
G1 X147.569 Y134.65 E.02415
G1 X206.35 Y193.431 E3.10102
G1 X206.35 Y194.078 E.02415
G1 X146.922 Y134.65 E3.13517
M73 P46 R1
G1 X146.274 Y134.65 E.02415
G1 X206.35 Y194.726 E3.16933
G1 X206.35 Y195.373 E.02415
G1 X145.627 Y134.65 E3.20348
M73 P47 R1
G1 X144.98 Y134.65 E.02415
G1 X206.35 Y196.02 E3.23764
G1 X206.35 Y196.668 E.02415
G1 X144.332 Y134.65 E3.27179
M73 P48 R1
G1 X143.685 Y134.65 E.02415
G1 X206.35 Y197.315 E3.30595
M73 P49 R1
G1 X206.35 Y197.963 E.02415
G1 X143.037 Y134.65 E3.3401
G1 X142.39 Y134.65 E.02415
G1 X206.35 Y198.61 E3.37426
M73 P50 R1
G1 X206.35 Y199.257 E.02415
G1 X141.743 Y134.65 E3.40841
G1 X141.095 Y134.65 E.02415
G1 X206.35 Y199.905 E3.44256
M73 P51 R1
G1 X206.35 Y200.552 E.02415
G1 X140.448 Y134.65 E3.47672
M73 P52 R1
G1 X139.8 Y134.65 E.02415
G1 X206.35 Y201.2 E3.51087
G1 X206.35 Y201.847 E.02415
G1 X139.153 Y134.65 E3.54503
M73 P53 R1
G1 X138.506 Y134.65 E.02415
G1 X206.35 Y202.494 E3.57918
M73 P54 R1
G1 X206.35 Y203.142 E.02415
G1 X137.858 Y134.65 E3.61334
G1 X137.211 Y134.65 E.02415
G1 X206.35 Y203.789 E3.64749
M73 P55 R1
G1 X206.35 Y204.437 E.02415
G1 X136.563 Y134.65 E3.68165
G1 X135.916 Y134.65 E.02415
G1 X206.35 Y205.084 E3.7158
M73 P56 R1
G1 X206.35 Y205.732 E.02415
G1 X135.268 Y134.65 E3.74995
M73 P57 R1
G1 X134.621 Y134.65 E.02415
G1 X206.35 Y206.379 E3.78411
G1 X206.35 Y207.026 E.02415
G1 X133.974 Y134.65 E3.81826
M73 P58 R1
G1 X133.65 Y134.65 E.01208
G1 X133.65 Y134.973 E.01207
G1 X206.027 Y207.35 E3.81827
M73 P59 R1
G1 X205.379 Y207.35 E.02415
G1 X133.65 Y135.621 E3.78412
G1 X133.65 Y136.268 E.02415
G1 X204.732 Y207.35 E3.74996
M73 P60 R1
G1 X204.084 Y207.35 E.02415
G1 X133.65 Y136.916 E3.71581
M73 P61 R1
G1 X133.65 Y137.563 E.02415
G1 X203.437 Y207.35 E3.68165
G1 X202.789 Y207.35 E.02415
G1 X133.65 Y138.211 E3.6475
M73 P62 R1
G1 X133.65 Y138.858 E.02415
G1 X202.142 Y207.35 E3.61335
M73 P63 R1
G1 X201.495 Y207.35 E.02415
G1 X133.65 Y139.505 E3.57919
G1 X133.65 Y140.153 E.02415
G1 X200.847 Y207.35 E3.54504
M73 P64 R0
G1 X200.2 Y207.35 E.02415
G1 X133.65 Y140.8 E3.51088
G1 X133.65 Y141.448 E.02415
G1 X199.552 Y207.35 E3.47673
M73 P65 R0
G1 X198.905 Y207.35 E.02415
G1 X133.65 Y142.095 E3.44257
M73 P66 R0
G1 X133.65 Y142.742 E.02415
G1 X198.258 Y207.35 E3.40842
G1 X197.61 Y207.35 E.02415
G1 X133.65 Y143.39 E3.37426
M73 P67 R0
G1 X133.65 Y144.037 E.02415
G1 X196.963 Y207.35 E3.34011
G1 X196.315 Y207.35 E.02415
G1 X133.65 Y144.685 E3.30596
M73 P68 R0
G1 X133.65 Y145.332 E.02415
G1 X195.668 Y207.35 E3.2718
M73 P69 R0
G1 X195.021 Y207.35 E.02415
G1 X133.65 Y145.979 E3.23765
G1 X133.65 Y146.627 E.02415
G1 X194.373 Y207.35 E3.20349
M73 P70 R0
G1 X193.726 Y207.35 E.02415
G1 X133.65 Y147.274 E3.16934
G1 X133.65 Y147.922 E.02415
G1 X193.078 Y207.35 E3.13518
M73 P71 R0
G1 X192.431 Y207.35 E.02415
G1 X133.65 Y148.569 E3.10103
G1 X133.65 Y149.216 E.02415
G1 X191.784 Y207.35 E3.06688
M73 P72 R0
G1 X191.136 Y207.35 E.02415
G1 X133.65 Y149.864 E3.03272
M73 P73 R0
G1 X133.65 Y150.511 E.02415
G1 X190.489 Y207.35 E2.99857
G1 X189.841 Y207.35 E.02415
G1 X133.65 Y151.159 E2.96441
M73 P74 R0
G1 X133.65 Y151.806 E.02415
G1 X189.194 Y207.35 E2.93026
G1 X188.546 Y207.35 E.02415
G1 X133.65 Y152.454 E2.8961
M73 P75 R0
G1 X133.65 Y153.101 E.02415
G1 X187.899 Y207.35 E2.86195
G1 X187.252 Y207.35 E.02415
G1 X133.65 Y153.748 E2.82779
M73 P76 R0
G1 X133.65 Y154.396 E.02415
G1 X186.604 Y207.35 E2.79364
G1 X185.957 Y207.35 E.02415
G1 X133.65 Y155.043 E2.75949
M73 P77 R0
G1 X133.65 Y155.691 E.02415
G1 X185.309 Y207.35 E2.72533
G1 X184.662 Y207.35 E.02415
G1 X133.65 Y156.338 E2.69118
M73 P78 R0
G1 X133.65 Y156.985 E.02415
G1 X184.015 Y207.35 E2.65702
G1 X183.367 Y207.35 E.02415
G1 X133.65 Y157.633 E2.62287
M73 P79 R0
G1 X133.65 Y158.28 E.02415
G1 X182.72 Y207.35 E2.58871
G1 X182.072 Y207.35 E.02415
G1 X133.65 Y158.928 E2.55456
M73 P80 R0
G1 X133.65 Y159.575 E.02415
G1 X181.425 Y207.35 E2.5204
G1 X180.778 Y207.35 E.02415
G1 X133.65 Y160.222 E2.48625
G1 X133.65 Y160.87 E.02415
M73 P81 R0
G1 X180.13 Y207.35 E2.4521
G1 X179.483 Y207.35 E.02415
G1 X133.65 Y161.517 E2.41794
G1 X133.65 Y162.165 E.02415
G1 X178.835 Y207.35 E2.38379
M73 P82 R0
G1 X178.188 Y207.35 E.02415
G1 X133.65 Y162.812 E2.34963
G1 X133.65 Y163.459 E.02415
G1 X177.541 Y207.35 E2.31548
M73 P83 R0
G1 X176.893 Y207.35 E.02415
G1 X133.65 Y164.107 E2.28132
G1 X133.65 Y164.754 E.02415
G1 X176.246 Y207.35 E2.24717
M73 P84 R0
G1 X175.598 Y207.35 E.02415
G1 X133.65 Y165.402 E2.21301
G1 X133.65 Y166.049 E.02415
G1 X174.951 Y207.35 E2.17886
G1 X174.303 Y207.35 E.02415
G1 X133.65 Y166.697 E2.14471
M73 P85 R0
G1 X133.65 Y167.344 E.02415
G1 X173.656 Y207.35 E2.11055
G1 X173.009 Y207.35 E.02415
G1 X133.65 Y167.991 E2.0764
M73 P86 R0
G1 X133.65 Y168.639 E.02415
G1 X172.361 Y207.35 E2.04224
G1 X171.714 Y207.35 E.02415
G1 X133.65 Y169.286 E2.00809
G1 X133.65 Y169.934 E.02415
G1 X171.066 Y207.35 E1.97393
M73 P87 R0
G1 X170.419 Y207.35 E.02415
G1 X133.65 Y170.581 E1.93978
G1 X133.65 Y171.228 E.02415
G1 X169.772 Y207.35 E1.90562
G1 X169.124 Y207.35 E.02415
G1 X133.65 Y171.876 E1.87147
M73 P88 R0
G1 X133.65 Y172.523 E.02415
G1 X168.477 Y207.35 E1.83732
G1 X167.829 Y207.35 E.02415
G1 X133.65 Y173.171 E1.80316
M73 P89 R0
G1 X133.65 Y173.818 E.02415
G1 X167.182 Y207.35 E1.76901
G1 X166.535 Y207.35 E.02415
G1 X133.65 Y174.465 E1.73485
G1 X133.65 Y175.113 E.02415
G1 X165.887 Y207.35 E1.7007
M73 P90 R0
G1 X165.24 Y207.35 E.02415
G1 X133.65 Y175.76 E1.66654
G1 X133.65 Y176.408 E.02415
G1 X164.592 Y207.35 E1.63239
G1 X163.945 Y207.35 E.02415
G1 X133.65 Y177.055 E1.59823
M73 P91 R0
G1 X133.65 Y177.702 E.02415
G1 X163.298 Y207.35 E1.56408
G1 X162.65 Y207.35 E.02415
G1 X133.65 Y178.35 E1.52993
G1 X133.65 Y178.997 E.02415
G1 X162.003 Y207.35 E1.49577
G1 X161.355 Y207.35 E.02415
G1 X133.65 Y179.645 E1.46162
M73 P92 R0
G1 X133.65 Y180.292 E.02415
G1 X160.708 Y207.35 E1.42746
G1 X160.06 Y207.35 E.02415
G1 X133.65 Y180.94 E1.39331
G1 X133.65 Y181.587 E.02415
G1 X159.413 Y207.35 E1.35915
M73 P93 R0
G1 X158.766 Y207.35 E.02415
G1 X133.65 Y182.234 E1.325
G1 X133.65 Y182.882 E.02415
G1 X158.118 Y207.35 E1.29084
G1 X157.471 Y207.35 E.02415
G1 X133.65 Y183.529 E1.25669
G1 X133.65 Y184.177 E.02415
G1 X156.823 Y207.35 E1.22254
M73 P94 R0
G1 X156.176 Y207.35 E.02415
G1 X133.65 Y184.824 E1.18838
G1 X133.65 Y185.471 E.02415
G1 X155.529 Y207.35 E1.15423
G1 X154.881 Y207.35 E.02415
G1 X133.65 Y186.119 E1.12007
G1 X133.65 Y186.766 E.02415
G1 X154.234 Y207.35 E1.08592
M73 P95 R0
G1 X153.586 Y207.35 E.02415
G1 X133.65 Y187.414 E1.05176
G1 X133.65 Y188.061 E.02415
G1 X152.939 Y207.35 E1.01761
G1 X152.292 Y207.35 E.02415
G1 X133.65 Y188.708 E.98345
G1 X133.65 Y189.356 E.02415
G1 X151.644 Y207.35 E.9493
M73 P96 R0
G1 X150.997 Y207.35 E.02415
G1 X133.65 Y190.003 E.91515
G1 X133.65 Y190.651 E.02415
G1 X150.349 Y207.35 E.88099
G1 X149.702 Y207.35 E.02415
G1 X133.65 Y191.298 E.84684
G1 X133.65 Y191.945 E.02415
G1 X149.055 Y207.35 E.81268
G1 X148.407 Y207.35 E.02415
G1 X133.65 Y192.593 E.77853
M73 P97 R0
G1 X133.65 Y193.24 E.02415
G1 X147.76 Y207.35 E.74437
G1 X147.112 Y207.35 E.02415
G1 X133.65 Y193.888 E.71022
G1 X133.65 Y194.535 E.02415
G1 X146.465 Y207.35 E.67607
G1 X145.818 Y207.35 E.02415
G1 X133.65 Y195.182 E.64191
G1 X133.65 Y195.83 E.02415
G1 X145.17 Y207.35 E.60776
M73 P98 R0
G1 X144.523 Y207.35 E.02415
G1 X133.65 Y196.477 E.5736
G1 X133.65 Y197.125 E.02415
G1 X143.875 Y207.35 E.53945
G1 X143.228 Y207.35 E.02415
G1 X133.65 Y197.772 E.50529
G1 X133.65 Y198.42 E.02415
G1 X142.58 Y207.35 E.47114
G1 X141.933 Y207.35 E.02415
G1 X133.65 Y199.067 E.43698
G1 X133.65 Y199.714 E.02415
G1 X141.286 Y207.35 E.40283
G1 X140.638 Y207.35 E.02415
G1 X133.65 Y200.362 E.36868
M73 P99 R0
G1 X133.65 Y201.009 E.02415
G1 X139.991 Y207.35 E.33452
G1 X139.343 Y207.35 E.02415
G1 X133.65 Y201.657 E.30037
G1 X133.65 Y202.304 E.02415
G1 X138.696 Y207.35 E.26621
G1 X138.049 Y207.35 E.02415
G1 X133.65 Y202.951 E.23206
G1 X133.65 Y203.599 E.02415
G1 X137.401 Y207.35 E.1979
G1 X136.754 Y207.35 E.02415
G1 X133.65 Y204.246 E.16375
G1 X133.65 Y204.894 E.02415
G1 X136.106 Y207.35 E.12959
G1 X135.459 Y207.35 E.02415
G1 X133.65 Y205.541 E.09544
G1 X133.65 Y206.188 E.02415
G1 X134.812 Y207.35 E.06129
G1 X134.164 Y207.35 E.02415
G1 X133.444 Y206.63 E.03798
; stop printing object First_Layer_Square_0.2.stl id:0 copy 0
EXCLUDE_OBJECT_END NAME=First_Layer_Square_0.2.stl_id_0_copy_0
G1 E-.5 F3600
M106 S0
;TYPE:Custom
; filament end gcode 
END_PRINT
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 481.18
; filament used [cm3] = 1.16
; filament used [g] = 1.44
; filament cost = 0.03; total filament used [g] = 1.44
; total filament cost = 0.03
; total layers count = 1
; estimated printing time (normal mode) = 2m 45s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; additional_cooling_fan_speed = 70
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_temperature_difference = 10
; before_layer_change_gcode = 
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 100%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 50
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 5
; chamber_temperature = 0
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; curr_bed_type = High Temp Plate
; default_acceleration = 7000
; default_filament_colour = ""
; default_filament_profile = 
; default_jerk = 0
; default_print_profile = 0.16mm Optimal @Bambu Lab X1 Carbon 0.4 nozzle
; deretraction_speed = 0
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = bridge_acceleration;brim_type;elefant_foot_compensation;filename_format;initial_layer_acceleration;inner_wall_acceleration;outer_wall_acceleration;reduce_crossing_wall;skirt_loops;top_shell_layers;travel_acceleration;travel_speed;filament_retraction_length;filament_retraction_speed;filament_start_gcode;nozzle_temperature;nozzle_temperature_initial_layer;deretraction_speed;gcode_flavor;machine_end_gcode;machine_max_acceleration_extruding;machine_max_acceleration_x;machine_max_acceleration_y;machine_max_jerk_e;machine_max_jerk_x;machine_max_jerk_y;machine_max_jerk_z;machine_start_gcode;print_host;printable_area;retract_when_changing_layer;retraction_length;wipe
; draft_shield = disabled
; elefant_foot_compensation = 0.1
; enable_arc_fitting = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = 1
; exclude_object = 1
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #F2754E
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.98
; filament_ids = GFL99
; filament_is_support = 0
; filament_max_volumetric_speed = 12
; filament_minimal_purge_on_wipe_tower = 15
; filament_retraction_length = 0.5
; filament_retraction_speed = 60
; filament_settings_id = PLA
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n{if nozzle_diameter[0] == 0.2}\n     PRESSURE_ADVANCE_SELECT Nozzle=0.2 FILAMENT=PLA\n{ else }\n    PRESSURE_ADVANCE_SELECT FILAMENT=PLA\n{ endif }"
; filament_type = PLA
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_infill_speed = 100
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @Tronxy";"Tronxy Generic PLA";"Tronxy X5SA 400 0.4 nozzle"
; initial_layer_acceleration = 1000
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 200
; interface_shells = 0
; internal_bridge_support_thickness = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.4
; internal_solid_infill_speed = 200
; ironing_flow = 10%
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.4
; machine_end_gcode = END_PRINT
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 6000
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 6000
; machine_max_acceleration_y = 6000
; machine_max_acceleration_z = 100
; machine_max_jerk_e = 2.5
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 0.3
; machine_max_speed_e = 60
; machine_max_speed_x = 500
; machine_max_speed_y = 500
; machine_max_speed_z = 10
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = 
; machine_start_gcode = START_PRINT T_BED=[first_layer_bed_temperature] T_EXTRUDER=[first_layer_temperature]
; machine_unload_filament_time = 0
; max_bridge_length = 10
; max_layer_height = 0.28
; max_travel_detour_distance = 0
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; minimum_sparse_infill_area = 15
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 200
; nozzle_temperature_initial_layer = 200
; nozzle_temperature_range_high = 230
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; outer_wall_acceleration = 4000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.4
; outer_wall_speed = 120
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_speed_classic = 0
; post_process = 
; precise_outer_wall = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Tronxy X5SA 400 0.4 nozzle"
; print_flow_ratio = 1
; print_host = 192.168.6.5:7126
; print_host_webui = 
; print_sequence = by layer
; print_settings_id = 0.20mm @Tronxy
; printable_area = 0x1,330x1,330x331,0x331
; printable_height = 400
; printer_model = Tronxy X5SA 400 Marlin Firmware
; printer_settings_id = TronXY X5SA
; printer_technology = FFF
; printer_variant = 0.4
; printhost_apikey = 
; printhost_authorization_type = key
; printhost_cafile = 
; printhost_password = 
; printhost_port = 
; printhost_ssl_ignore_revoke = 0
; printhost_user = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 1
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 1
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 0
; retraction_length = 0.8
; retraction_minimum_travel = 2
; retraction_speed = 60
; role_based_wipe_speed = 1
; scan_first_layer = 0
; seam_gap = 15%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 2
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 10
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 200
; spiral_mode = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_pattern = rectilinear
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.4
; support_material_interface_fan_speed = -1
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thumbnails = 300x300
; timelapse_type = 0
; top_shell_layers = 3
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 3000
; top_surface_jerk = 9
; top_surface_line_width = 0.4
; top_surface_pattern = monotonic
; top_surface_speed = 100
; travel_acceleration = 9000
; travel_jerk = 12
; travel_speed = 150
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_diameter = 5
; tree_support_branch_distance = 5
; tree_support_brim_width = 3
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_infill_order = inner wall/outer wall/infill
; wall_loops = 2
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_distance = 2
; wipe_on_loops = 1
; wipe_speed = 80%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 155.000
; wipe_tower_y = 220.000
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0
; z_hop_types = Normal Lift
; first_layer_bed_temperature = 60
; bed_shape = 0x1,330x1,330x331,0x331
; first_layer_temperature = 200
; first_layer_height = 0.200
; CONFIG_BLOCK_END


