; HEADER_BLOCK_START
; generated by OrcaSlicer 1.6.4-beta3 on 2023-08-19 at 10:12:03
; total layer number: 1
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START
; thumbnail begin 300x300 5812
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAQzElEQVR4Ae3d745U530H8HlhIddBLU
; 4wEIPx0kBthwhT5EROG9UojhrHchQSVziqmmhrVZHlVC2NWilqq64U5UXe7SVwCVwCl8Al+FY631ke
; GC0zu2dmzv/z+Ugr/rOw88zvPOd3nu/zzGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQG+98tK5GUCvXf3a7dkvrz2c
; fXbtcHbnG/dmAL10f16k3n9t/9mP3/36vdlP3zgw2wL6I7Oqf/zLw9mFl2+/8GuX/uz2YraV3wPQqb
; +//GD2izcPT/19dy89mP3g4r7ZFtC+FJ5/+tbD2fU/v1v5z2SW9c83Hs7Ov7w3A2jF239xd9Gv2kYK
; XW4Rv39hfwbQqBSqFKxd5e9I4XKLCNQut3O5BTz70t6sLq+e2Vv0wCx/AGqTovLDbz6YNeV75/c15I
; HdpIBkucLrrzS/JOHy/HNkzZaGPLCxzHi2baxvKwUyRevDBmdzwMhkXdUmyxXqloZ8lj+4RQTWKjnA
; PijLHzTkgRd8Mr8Vy21g38gjAs9kVvUvf/Wwlcb6tuQRgco5wL74+Eo/Z4FAg7bJAfaFPCJMSJ7AfX
; 7j0WzISkM+/S1gpO6P7KmbhjyMUNlg79yZvdnYpCGfXpyGPIxA3sxZsjB2NgiEAcsb9zdvPer1coW6
; Hc0kNeRhUDLTyFPAKUqhvnf1wAaBMAT7N4a5XKFuNgiEHisb7HUpxWHVR1fyubPzgzwi9EhugZrYYC
; +zlLzZc4v50eWDxUdWxudzpZmfn8+3H105ePbxd/Pm9/JHfu9P5j+fxn++nz+Tj0/nf09+rnzk1/L5
; UnjrLnI35jNODXnoWB05wDSoU5RS9H70+lHhyPdTnG59/V6rTfssu7h57t7sg6eFrvxbUhR3LWZZ/p
; A1W5Y/QAe2yQHmzZ7ilGKUP59i8DcXHgxifVb+jd89v78oYj+7eriYtWXWtGkBSh7RBoHQkhSdqhvs
; 5ffmTf3BpYOnT86GUZyqyv/lby8erTPL/+/916oVsJJHdIsIDaqywV5mUKUnlAI1JSlAKWC5pcwMLL
; eR64qSDQKhQckBZgaxSt50P33jcDHL0KN57vrTZnuZfa0qXvKIUKN1OcAUqU/ffLh4M1rZfbqL86Z7
; ilfWqeVrt1yg5BGhBscb63lDlWUAitT2MvPK1zC3jstFSh4RtlA22Ns7e3fx48wIfnz5oNHDTKeo9L
; wWt9sXjgqVPCJsII3ich5g2WlhSgHmrpSDXDPDSrGSR4RTpFClYKVQpW/1tZf2ZrTr4tMFpnkNMrOV
; R4RjSg4w/aoUKrqXIpWileKVD8sfYHZ02/en975aFKqzZlS9U7aryULTvFZmW0xSBv7vbz1ebLKnwd
; t/uVX81fWHs//6zmOvF9OSxu4f7jx59hSQ4cjt+3/cfLyYbcHo7c+v0gkfM2w/uPhg9tt3HrlFZJxK
; Y32MJ9dMVVbIyyMyOp+84Yj1MZNHZBTKBntl7yYDepzSz/p073Ax25JHZJAyiMuK9chA/vV1kY8xOR
; 6hChsEMigZxF++/WixYn3Vr4l8jMNyhGrVr6Uh7+JEr2Wg/vHOV6dm/xxBNWwlQnWSZBP/990nepf0
; U1aqZyFoVa/OnxY6gmpYypPeqomEXJDSw8yHixO9kEH8f7efzB7crF6sljmCahjSk9xme5+8ron15G
; J22qwMGpVBnB0sv3hru2JVlK1N9Dz6JwUns+ddt/j5+ZuHs9/NL2ouTrQuAy6FKvuE71qslv9OT5j6
; JcVlXWN9Gylaeehig0Bak0GcPkZuBesqVsty2+AIqu5VPUptUyla5WAMFycalattBnGK1ec3Hs2a4g
; iq7lQ5Sm1XKVp5bV2caER5OhRlnVUbRD7a1WaEqqyKz2trg0Bqk6l7GcSlAdumErAV+WhOiVC1uXd+
; WURcLkZ5WmyDQLa2ahBnZtXVgPr4igB1E44fpdamsuShjKlLT/eTd3FiI6sGcelfdSkDOQPcE6bdlR
; xg169plrRkprXMxYlKMohXPR1Kc3TdMfFtKw15ecTt5fVs8qHJplYlHlycONG6p0NtNtk3kYa8POLm
; 7vf06euqPmW5OOW1hmdOGsTpY/VVeh65fRX5OF3pSfZ1x9fShF/F02IWjo4lP1w7iMtamb67e+mByM
; cJygnafZextm4xabk4achP1GlPh7pYwrCLo+Kr57GsRKjaXK6wq9NmUi5OE7Nql8hVUqyGNihsEPhc
; iVANTVnqcBIXp4k4aZfIZRkIPxxwzmvqkY8+LFfYRZW+pIvTyFXZJbLoc6O9qilGPpYjVEP3WcVdIu
; xeOzKb7hKZ3z+mRXtTiXwsR6jGIDOnqhfYvLZ2rx2BDOJNb+3GMLs6bsyRjy5ygG2pOssq7F47UOlB
; bTOIh967Os3YIh9d5gDbsMksqygXJw35gdhll8ghLWPY1hgiH+siVGOzy9Iau9cOwC6DeGjrrnYx5M
; hHGxvs9UlmkdteXMrFyS1iz9QxiDMzm9o0emiRj8yc+xJCb0vG5LrIThV2r+2ZugbxJmcKjskQIh+n
; RajGro6Zvzxix8ogvvDy7m+0vIh5005ZXyMfY2+sV7HLbeEyu9d2pO5BPMXbwVX6FPmoGqGagrwuu9
; wWHleeFpttNaypXSKn0myvog+Rj6oRqimpe4zaILBhTQ5iBetFXUU+NolQTUkT/Se71zakyUGsf7Ve
; m5GPTSNUU5Oi0tTrYPfamrQxiDMITItP1nTkY5sI1dQ0nXEtT4stf9hSvnhtDGK9kmqaiHxsG6Gaqj
; ob7+vYIHBDZcV5W4P4377dvwMm+qyuyMcuEaqpaqvXmtncP+wduvM4TReDWMN9c7tGPqaQA2xCGzOs
; ojwtlkdco6tBrGBtZ5vIx9RygHVbPtq+LVPfvfYFXQ7ik45WopqqkY8p5gDrVteK903JIz6Vo5e63J
; 8pL74lDbs7KfJRNtirI0I1dXmvdBmrmWwesS+7RI5tO+SuHY98yAHWqw/nZE4uj5gmXl8GsYJVv9KQ
; H/rJNX3Up4N9x7Z77Vp9OuVDwapfiVCJfNSvTwVrUhGqvpzyoWDV6/ggFvmoVx8K1qQjVF2f8qHpXo
; +TBrHIR326brq3lT7pta5P+bAOazdVB7HIx+66WIcV+ZwiVMd0dcpHIghsbpsIlcjHbrq4uIpQnaCL
; Uz7GeHBq03YZxCIf22u7YIlQVdD2qlor3TdT1yBO8/iLtx65RdxAW2NVhGoLba2q9RSrmiYGscjHZt
; ooWF2nTwatjVW1Te7kOBZND+JcnLpqKA9F0zvj9iV9MgpNrqrNC2Vpw2ptDmJHUJ2syZ1xRaga0OQp
; H5Y2vKirQTyZyMeGmrgdbOoUKp5q6pQPTwqfy9e466dDjqB6Ud0X1Tz0SLGiBXVHPlIAHS3Vr6dD5e
; KU13rq6u5f3fego30l8lFHoSlvjinr6yCe7B5MS3I7WMdsMxek/fnM9dyZvRkdqSvyMdX1WEfH0x/2
; ehCXi9NUG/Jfvr37QSlygD1SR+RjireFQ3s6NMU8Ysb0LoWm7VOoqGjXyMeUbgvL06G9s3dnQ3M0I5
; xOQ36XHJ8c4ADsEvnIjGPsV+/0qYY+iMvFaewbBJbZ0TbkAAdk28hHrtpp8I5VGq5juu3t0+61TcgM
; adOZpBzggGWDwE0jH2M8g23Mu0T2ZffaJuQCswk5wBHYNPJx+ZXbo5plpWBP4elQ17vX1i3/l6qNcj
; nAEdok8jGGIO4UB3HZvXboyx8y9qrOruQAR6xq5GPoe71P/elQV7vX1iUXzNMuNH2IUNGCqpGPIS5U
; NIif62L32jpUmV1prE/QaZGPoa3LMohfNMQNAk8L4ssBTthpkY88Nh/CrWEG8fuv7c9YbSh5xBSidc
; VoCBEqWnJS5KOu4GkTDOLq+p5HPOlWUGOdF6yLfJTbir5dnQ3i7fQ1j7jqVnDIESpasC7y0adtlA3i
; 3eX1/PX1/uQRU0CPPygZQ4SKlqyKfGRQdd3szL/LIK5HU7vXbiqv6fGFvXmNbSjJRlZFPro8JMEgbk
; aXecR8zuW9rsYcoaIly5GPLvpZBnHzXj1ztFC4zRn08Z0YphKhogUl8pGeRwbaF2+3c2KxXSLb9b3z
; +6015L98OoYypuQAaUSJfKSAZYfTpga2XSK7U8LvTTbkU6AuvHzbBns0r0Q+cqvYxO2hQdy9vKYpWk
; 3kEXMhyhgSoaI1pZeVQV1n0TKI+yUN+TrziClWuSCJUNGJRD6yHXOm+LsMajnA/qorj5hV7P/5ncci
; VHQr/ax///bj2e9uPt6qaNklchh2ySP+/tbj2YP5+EjfCnohTfgMzKrNWrtEDs+mu9emuP3hzhMRKv
; opA/ng9pNTbx/kAIetyu61GQt/vPOVniT9Vnoeq54wlRygQTx8J+1emwvSpgdIQKeOP2HKjz+/sfuR
; 4/THqt1rx3aUGhNSIh9Z1WyXyPFKwUrhEqFiFNqMfNA+ESpGJ5GP7ME09COoeM6TXkatRD7GfLz6VG
; R3BREqJiFN2Sx/GPLZh1OVW/v/vvXEk16mJTOsPEXMYlO3if2X1yiv1b++83gGk5UnTP/z7pPZb995
; pHD1UNlZ4U/vfSVCBVEiH/euHi5mXQpX9/IafHbt4ew3T8PtGutwTIl83PnGvsLVkXzNfz6fUf348o
; EIFZxmOfKR5nyeRiXm46lis7KwN4Uq27+IUMEGjkc+cjuSwpUrfl9PoR6qfE0/WdoSWYQKtnR8D6Z8
; +9fz28XsXFlmAmwus6kPv3mwuO1bdr+Gjfpg0tKQzyzgeD/r4tOf/9W3jnpditfJUoh+8ebDxUz1+C
; w1X79cBM6d2ZsBNbh76cHaPGJ6LSlemSGYeT2XIvXpmiJVaKxDQ45mAg9P7GNl5vXd8/uLMG6ZmU2l
; gKX/VHpS+ThpxpSvSZYsWK4ADcobLTOG71/Yr/R7b837YOXosLEVsMyg8rVIccq3t16t1n/K18MGe9
; CizCa2CVHn9rHMwMqbPX9Xn58+5v+Y4pSC+/GVw8W/Pf/ubZYdpFBZrgAdyBs5a7R2fbJ17ezd2QeX
; jvZ0Wi5k+X6KWRuzshTM/D8y+/lo/vTuR68fPPu33L10sPOtW/4PWVsFdCynUDexQWD+vhSzm+fuPS
; to+Tz59mdXDxdF7SdXnn+kef3R/Nu1H/NClD+Xb8vxZilI+fF781nf3vxzNSGfwwZ70CNZ/pA1W+I8
; z9lgD3ouecQPzSaeLfMAeq7kEae4Hiv/59yaaqzDgJQ84pSiJinUv7ymsQ6DdTyPOFZllT8wcOvyiG
; MgBwgjdVIecYjkAGHkMiPJ+YhD3lerbLDX1LotoEc2ySP2TVbeW64AE7RtHrErKVT5NwMTVVcesUkl
; B3j2pb0ZQGN5xF2lsS4HCLyg5BH70JBP4cxyBTlAYK0Uiq7ziGXDQYBKusojygECW2kzjygHCNSi6T
; xi2cwPoBZpyGe2VWce0QZ7QKPSkK9jNiQHCLSiNOS3Wf5QcoAa60BrSkN+kzxiYjVOrgE6k4Z8lTzi
; /Yntfgr0VNkgcFUwObePObzUBntArxzfIDBFLEsWAHrpaMvih4tZleUKQO9N8XgxAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAABiO/wc6NM9OACYstAAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.46mm
; infill extrusion width = 0.64mm
; solid infill extrusion width = 0.56mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.46mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=parametric_bed_center_calibration_crosshair.stl_id_0_copy_0 CENTER=165,165 POLYGON=[[40,40],[290,40],[290,290],[40,290],[40,40]]
M73 P0 R2
;TYPE:Custom
START_PRINT T_BED=60 T_EXTRUDER=220
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode

    PRESSURE_ADVANCE_SELECT FILAMENT=PLA
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

SET_VELOCITY_LIMIT ACCEL=1000 ACCEL_TO_DECEL=500
G1 E-.8 F3000
G1 X37.904 Y38.116 F12000
G1 Z.2
G1 E.8 F1800
;TYPE:Skirt
;WIDTH:0.5
G1 F3000
G1 X38.552 Y37.471 E.03407
G1 X40 Y37.086 E.0558
G1 X290 Y37.086 E9.31155
M73 P3 R2
G1 X291.462 Y37.479 E.05638
G1 X292.529 Y38.552 E.05638
G1 X292.914 Y40 E.0558
G1 X292.914 Y290 E9.31155
M73 P7 R2
G1 X292.521 Y291.462 E.05638
G1 X291.448 Y292.529 E.05638
G1 X290 Y292.914 E.0558
G1 X40 Y292.914 E9.31155
M73 P10 R2
G1 X38.538 Y292.521 E.05638
G1 X37.471 Y291.448 E.05638
G1 X37.086 Y290 E.0558
G1 X37.086 Y40 E9.31155
M73 P14 R2
G1 X37.479 Y38.538 E.05638
G1 X37.875 Y38.144 E.02082
G1 X38.16 Y38.474 F12000
G1 F3000
G1 X38.985 Y37.762 E.04059
G1 X40 Y37.543 E.03866
G1 X290 Y37.543 E9.31155
M73 P17 R2
G1 X291.331 Y37.935 E.05169
G1 X292.238 Y38.985 E.05169
G1 X292.457 Y40 E.03866
G1 X292.457 Y290 E9.31155
M73 P20 R1
G1 X292.065 Y291.331 E.05169
G1 X291.015 Y292.238 E.05169
G1 X290 Y292.457 E.03866
G1 X40 Y292.457 E9.31155
M73 P24 R1
G1 X38.669 Y292.065 E.05169
G1 X37.762 Y291.015 E.05169
G1 X37.543 Y290 E.03866
G1 X37.543 Y40 E9.31155
M73 P27 R1
G1 X37.935 Y38.669 E.05169
G1 X38.13 Y38.5 E.00961
; printing object parametric_bed_center_calibration_crosshair.stl id:0 copy 0
G1 E-.8
EXCLUDE_OBJECT_START NAME=parametric_bed_center_calibration_crosshair.stl_id_0_copy_0
G1 X40.256 Y289.744 F12000
M73 P28 R1
G1 E.8 F1800
;TYPE:Outer wall
G1 F3000
G1 X40.25 Y179.514 E4.10567
M73 P30 R1
G2 X40.35 Y177 I-20.792 J-2.086 E.09375
G2 X40.279 Y173.492 I-69.712 J-.346 E.13071
G1 X40.25 Y172.496 E.03709
G1 X40.25 Y157.504 E.55842
G2 X40.349 Y154.001 I-276.931 J-9.598 E.13051
G2 X40.338 Y151.489 I-110.68 J-.744 E.09356
G2 X40.25 Y150.486 I-11.323 J.484 E.03751
G1 X40.256 Y40.256 E4.10567
M73 P32 R1
G1 X150.486 Y40.25 E4.10567
M73 P33 R1
G1 X150.978 Y40.304 E.01843
G2 X151.997 Y40.348 I1.006 J-11.464 E.03801
G2 X156.508 Y40.279 I1.03 J-79.98 E.16805
G1 X157.504 Y40.25 E.03709
G1 X172.496 Y40.25 E.55842
G2 X175.999 Y40.349 I9.598 J-276.934 E.13051
G2 X179.022 Y40.304 I.889 J-41.779 E.11263
G1 X179.514 Y40.25 E.01843
G1 X289.744 Y40.256 E4.10567
M73 P35 R1
G1 X289.75 Y150.486 E4.10567
M73 P36 R1
G2 X289.65 Y153 I20.792 J2.086 E.09375
G2 X289.721 Y156.508 I69.712 J.346 E.13071
G1 X289.75 Y157.504 E.03709
M73 P37 R1
G1 X289.75 Y172.496 E.55842
G2 X289.651 Y175.999 I276.931 J9.598 E.13051
G2 X289.662 Y178.511 I110.68 J.744 E.09356
G2 X289.75 Y179.514 I11.323 J-.484 E.03751
G1 X289.744 Y289.744 E4.10567
M73 P38 R1
G1 X179.514 Y289.75 E4.10567
M73 P40 R1
G2 X177 Y289.65 I-2.086 J20.792 E.09375
G2 X173.492 Y289.721 I-.346 J69.712 E.13071
G1 X172.496 Y289.75 E.03709
G1 X157.504 Y289.75 E.55842
G2 X154.001 Y289.651 I-9.598 J276.931 E.13051
G2 X151.489 Y289.662 I-.744 J110.69 E.09356
G2 X150.486 Y289.75 I.484 J11.323 E.03751
G1 X40.296 Y289.744 E4.10418
M73 P42 R1
G1 E-.8
G1 X165.325 Y289.272 F12000
G1 X167.169 Y289.256
G1 X169.337 Y289.199
G1 X179.547 Y288.819
G1 E.8 F1800
G1 F3000
G2 X288.746 Y180.194 I-14.554 J-123.831 E6.18367
M73 P45 R1
G1 X288.819 Y179.547 E.02426
G1 X289.525 Y179.587 E.02632
G1 X289.525 Y289.525 E4.09477
M73 P46 R1
G1 X179.587 Y289.525 E4.09477
M73 P48 R1
G1 X179.549 Y288.859 E.02483
G1 E-.8
G1 X169.337 Y289.199 F12000
G1 X167.169 Y289.256
G1 X165.325 Y289.272
G1 X165.325 Y40.728
M73 P49 R1
G1 X167.169 Y40.744
G1 X169.337 Y40.801
G1 X179.547 Y41.181
G1 E.8 F1800
G1 F3000
G1 X179.587 Y40.475 E.02632
G1 X289.525 Y40.475 E4.09477
M73 P50 R1
G1 X289.525 Y150.413 E4.09477
M73 P52 R1
G1 X288.819 Y150.453 E.02632
G2 X179.587 Y41.185 I-123.806 J14.534 E6.20656
M73 P54 R1
G1 E-.8
G1 X169.337 Y40.801 F12000
G1 X167.169 Y40.744
G1 X165.325 Y40.728
G1 X164.675 Y40.728
G1 X162.831 Y40.744
G1 X160.663 Y40.801
G1 X158.496 Y40.895
G1 X156.331 Y41.028
G1 X154.169 Y41.198
G1 X151.665 Y41.408
G1 X147.704 Y41.934
G1 X145.559 Y42.255
G1 X143.42 Y42.613
G1 X141.287 Y43.008
G1 X139.162 Y43.441
G1 X137.044 Y43.91
G1 X134.935 Y44.416
G1 X132.835 Y44.959
G1 X130.745 Y45.539
G1 X128.665 Y46.155
G1 X126.597 Y46.807
G1 X124.54 Y47.496
G1 X122.495 Y48.22
G1 X120.464 Y48.979
G1 X118.446 Y49.774
G1 X116.442 Y50.604
G1 X114.453 Y51.469
G1 X112.479 Y52.368
G1 X110.521 Y53.302
G1 X108.58 Y54.27
G1 X106.656 Y55.272
G1 X104.75 Y56.307
G1 X102.862 Y57.375
G1 X100.994 Y58.475
M73 P55 R1
G1 X99.144 Y59.609
G1 X97.315 Y60.774
G1 X95.506 Y61.971
G1 X93.719 Y63.2
G1 X91.953 Y64.459
G1 X90.209 Y65.75
G1 X88.489 Y67.07
G1 X86.791 Y68.42
G1 X85.117 Y69.8
G1 X83.468 Y71.208
G1 X81.844 Y72.646
G1 X80.245 Y74.111
G1 X78.671 Y75.604
G1 X77.124 Y77.124
G1 X75.604 Y78.671
G1 X74.111 Y80.245
G1 X72.646 Y81.844
G1 X71.208 Y83.468
G1 X69.8 Y85.117
G1 X68.42 Y86.791
G1 X67.07 Y88.489
G1 X65.75 Y90.209
G1 X64.459 Y91.953
G1 X63.2 Y93.719
G1 X61.971 Y95.506
G1 X60.774 Y97.315
G1 X59.609 Y99.144
G1 X58.475 Y100.994
G1 X57.375 Y102.862
G1 X56.307 Y104.75
G1 X55.272 Y106.656
G1 X54.27 Y108.58
G1 X53.302 Y110.521
G1 X52.368 Y112.479
G1 X51.469 Y114.453
G1 X50.604 Y116.442
G1 X49.774 Y118.446
G1 X48.979 Y120.464
G1 X48.22 Y122.495
G1 X47.496 Y124.54
G1 X46.807 Y126.597
G1 X46.155 Y128.665
G1 X45.539 Y130.745
G1 X44.959 Y132.835
G1 X44.416 Y134.935
G1 X43.91 Y137.044
G1 X43.441 Y139.162
G1 X43.008 Y141.287
G1 X42.613 Y143.42
G1 X42.255 Y145.559
G1 X41.934 Y147.704
G1 X41.408 Y151.665
G1 X41.198 Y154.169
G1 X41.028 Y156.331
G1 X40.476 Y164.925
G1 E.8 F1800
G1 F3000
G3 X40.699 Y157.617 I119.756 J-.004 E.27235
G3 X40.85 Y154.139 I105.583 J2.85 E.12967
G1 X41.06 Y151.97 E.08116
G3 X41.307 Y150.672 I9.423 J1.12 E.04925
G3 X150.672 Y41.307 I123.679 J14.313 E6.21571
M73 P57 R1
G3 X151.528 Y41.12 I2.144 J7.795 E.03264
G3 X157.188 Y40.716 I6.411 J49.939 E.21143
M73 P58 R1
G3 X163.89 Y40.485 I8.342 J144.428 E.24982
G1 X164.925 Y40.476 E.03855
G1 X164.925 Y164.925 E4.63527
M73 P59 R1
G1 X40.516 Y164.925 E4.63378
M73 P61 R0
G1 E-.8
G1 X40.895 Y158.496 F12000
G1 X41.028 Y156.331
G1 X41.198 Y154.169
G1 X41.408 Y151.665
G1 X41.934 Y147.704
G1 X42.255 Y145.559
G1 X42.613 Y143.42
G1 X43.008 Y141.287
G1 X43.441 Y139.162
G1 X43.91 Y137.044
G1 X44.416 Y134.935
G1 X44.959 Y132.835
G1 X45.539 Y130.745
G1 X46.155 Y128.665
G1 X46.807 Y126.597
G1 X47.496 Y124.54
G1 X48.22 Y122.495
G1 X48.979 Y120.464
G1 X49.774 Y118.446
G1 X50.604 Y116.442
G1 X51.469 Y114.453
G1 X52.368 Y112.479
G1 X53.302 Y110.521
G1 X54.27 Y108.58
G1 X55.272 Y106.656
G1 X56.307 Y104.75
G1 X57.375 Y102.862
G1 X58.475 Y100.994
G1 X59.609 Y99.144
G1 X60.774 Y97.315
G1 X61.971 Y95.506
G1 X63.2 Y93.719
G1 X64.459 Y91.953
G1 X65.75 Y90.209
G1 X67.07 Y88.489
G1 X68.42 Y86.791
G1 X69.8 Y85.117
G1 X71.208 Y83.468
G1 X72.646 Y81.844
G1 X74.111 Y80.245
G1 X75.604 Y78.671
G1 X77.124 Y77.124
G1 X78.671 Y75.604
G1 X80.245 Y74.111
G1 X81.844 Y72.646
G1 X83.468 Y71.208
G1 X85.117 Y69.8
G1 X86.791 Y68.42
G1 X88.489 Y67.07
G1 X90.209 Y65.75
M73 P62 R0
G1 X91.953 Y64.459
G1 X93.719 Y63.2
G1 X95.506 Y61.971
G1 X97.315 Y60.774
G1 X99.144 Y59.609
G1 X100.994 Y58.475
G1 X102.862 Y57.375
G1 X104.75 Y56.307
G1 X106.656 Y55.272
G1 X108.58 Y54.27
G1 X110.521 Y53.302
G1 X112.479 Y52.368
G1 X114.453 Y51.469
G1 X116.442 Y50.604
G1 X118.446 Y49.774
G1 X120.464 Y48.979
G1 X122.495 Y48.22
G1 X124.54 Y47.496
G1 X126.597 Y46.807
G1 X128.665 Y46.155
G1 X130.745 Y45.539
G1 X132.835 Y44.959
G1 X134.935 Y44.416
G1 X137.044 Y43.91
G1 X139.162 Y43.441
G1 X141.287 Y43.008
G1 X150.453 Y41.181
G1 E.8 F1800
G1 F3000
G2 X41.181 Y150.453 I14.534 J123.806 E6.20805
M73 P64 R0
G1 X40.475 Y150.413 E.02632
G1 X40.475 Y40.475 E4.09477
M73 P66 R0
G1 X150.413 Y40.475 E4.09477
M73 P67 R0
G1 X150.451 Y41.141 E.02483
G1 E-.8
G1 X160.663 Y40.801 F12000
G1 X162.831 Y40.744
G1 X164.675 Y40.728
G1 X164.675 Y289.272
M73 P68 R0
G1 X162.831 Y289.256
G1 X160.663 Y289.199
G1 X150.453 Y288.819
G1 E.8 F1800
G1 F3000
G1 X150.413 Y289.525 E.02632
G1 X40.475 Y289.525 E4.09477
M73 P70 R0
G1 X40.475 Y179.587 E4.09477
M73 P71 R0
G1 X41.181 Y179.547 E.02632
G2 X150.413 Y288.815 I123.806 J-14.534 E6.20656
M73 P74 R0
G1 E-.8
G1 X141.287 Y286.992 F12000
G1 X139.162 Y286.559
G1 X137.044 Y286.09
G1 X134.935 Y285.584
G1 X132.835 Y285.041
G1 X130.745 Y284.461
G1 X128.665 Y283.845
G1 X126.597 Y283.193
G1 X124.54 Y282.504
G1 X122.495 Y281.78
G1 X120.464 Y281.021
G1 X118.446 Y280.226
G1 X116.442 Y279.396
G1 X114.453 Y278.531
G1 X112.479 Y277.632
G1 X110.521 Y276.698
G1 X108.58 Y275.73
G1 X106.656 Y274.728
G1 X104.75 Y273.693
G1 X102.862 Y272.625
G1 X100.994 Y271.525
G1 X99.144 Y270.391
G1 X97.315 Y269.226
G1 X95.506 Y268.029
G1 X93.719 Y266.8
G1 X91.953 Y265.541
G1 X90.209 Y264.25
G1 X88.489 Y262.93
G1 X86.791 Y261.58
G1 X85.117 Y260.2
G1 X83.468 Y258.792
G1 X81.844 Y257.354
G1 X80.245 Y255.889
G1 X78.671 Y254.396
G1 X77.124 Y252.876
G1 X75.604 Y251.329
G1 X74.111 Y249.755
G1 X72.646 Y248.156
G1 X71.208 Y246.532
G1 X69.8 Y244.883
G1 X68.42 Y243.209
G1 X67.07 Y241.511
G1 X65.75 Y239.791
G1 X64.459 Y238.047
G1 X63.2 Y236.281
G1 X61.971 Y234.494
G1 X60.774 Y232.685
G1 X59.609 Y230.856
G1 X58.475 Y229.006
G1 X57.375 Y227.138
G1 X56.307 Y225.25
G1 X55.272 Y223.344
G1 X54.27 Y221.42
G1 X53.302 Y219.479
G1 X52.368 Y217.521
G1 X51.469 Y215.547
G1 X50.604 Y213.558
G1 X49.774 Y211.554
G1 X48.979 Y209.536
G1 X48.22 Y207.505
G1 X47.496 Y205.46
G1 X46.807 Y203.403
G1 X46.155 Y201.335
G1 X45.539 Y199.255
G1 X44.959 Y197.165
G1 X44.416 Y195.065
G1 X43.91 Y192.956
G1 X43.441 Y190.838
G1 X43.008 Y188.713
G1 X42.613 Y186.58
G1 X42.255 Y184.441
G1 X41.934 Y182.296
G1 X41.408 Y178.335
G1 X41.198 Y175.831
G1 X41.028 Y173.669
G1 X40.476 Y165.075
G1 E.8 F1800
G1 F3000
G1 X164.925 Y165.075 E4.63527
M73 P76 R0
G1 X164.925 Y289.524 E4.63527
M73 P78 R0
G3 X157.617 Y289.301 I-.004 J-119.756 E.27235
G3 X154.139 Y289.15 I2.85 J-105.583 E.12967
G1 X151.97 Y288.94 E.08116
G3 X150.672 Y288.693 I1.12 J-9.423 E.04925
G3 X41.307 Y179.328 I14.313 J-123.679 E6.21571
M73 P80 R0
G3 X41.12 Y178.472 I7.795 J-2.144 E.03264
G3 X40.716 Y172.812 I49.939 J-6.411 E.21143
G3 X40.476 Y165.115 I145.454 J-8.393 E.28687
G1 E-.8
G1 X41.028 Y156.331 F12000
M73 P81 R0
G1 X41.198 Y154.169
G1 X41.408 Y151.665
G1 X41.934 Y147.704
G1 X42.255 Y145.559
G1 X42.613 Y143.42
G1 X43.008 Y141.287
G1 X43.441 Y139.162
G1 X43.91 Y137.044
G1 X44.416 Y134.935
G1 X44.959 Y132.835
G1 X45.539 Y130.745
G1 X46.155 Y128.665
G1 X46.807 Y126.597
G1 X47.496 Y124.54
G1 X48.22 Y122.495
G1 X48.979 Y120.464
G1 X49.774 Y118.446
G1 X50.604 Y116.442
G1 X51.469 Y114.453
G1 X52.368 Y112.479
G1 X53.302 Y110.521
G1 X54.27 Y108.58
G1 X55.272 Y106.656
G1 X56.307 Y104.75
G1 X57.375 Y102.862
G1 X58.475 Y100.994
G1 X59.609 Y99.144
G1 X60.774 Y97.315
G1 X61.971 Y95.506
G1 X63.2 Y93.719
G1 X64.459 Y91.953
G1 X65.75 Y90.209
G1 X67.07 Y88.489
G1 X68.42 Y86.791
G1 X69.8 Y85.117
G1 X71.208 Y83.468
G1 X72.646 Y81.844
G1 X74.111 Y80.245
G1 X75.604 Y78.671
G1 X77.124 Y77.124
G1 X78.671 Y75.604
G1 X80.245 Y74.111
G1 X81.844 Y72.646
G1 X83.468 Y71.208
G1 X85.117 Y69.8
G1 X86.791 Y68.42
G1 X88.489 Y67.07
G1 X90.209 Y65.75
G1 X91.953 Y64.459
G1 X93.719 Y63.2
G1 X95.506 Y61.971
G1 X97.315 Y60.774
G1 X99.144 Y59.609
G1 X100.994 Y58.475
G1 X102.862 Y57.375
G1 X104.75 Y56.307
G1 X106.656 Y55.272
G1 X108.58 Y54.27
G1 X110.521 Y53.302
G1 X112.479 Y52.368
G1 X114.453 Y51.469
G1 X116.442 Y50.604
G1 X118.446 Y49.774
G1 X120.464 Y48.979
G1 X122.495 Y48.22
G1 X124.54 Y47.496
G1 X126.597 Y46.807
G1 X128.665 Y46.155
G1 X130.745 Y45.539
G1 X132.835 Y44.959
G1 X134.935 Y44.416
G1 X137.044 Y43.91
G1 X139.162 Y43.441
G1 X141.287 Y43.008
G1 X143.42 Y42.613
G1 X145.559 Y42.255
G1 X147.704 Y41.934
G1 X151.665 Y41.408
G1 X154.169 Y41.198
G1 X156.331 Y41.028
G1 X165.075 Y40.476
G1 E.8 F1800
G1 F3000
G3 X172.812 Y40.716 I-.655 J145.694 E.28836
G3 X177.592 Y41.016 I-.686 J49.176 E.17845
G3 X179.328 Y41.307 I-1.202 J12.503 E.06558
G3 X288.693 Y150.672 I-14.313 J123.679 E6.21571
M73 P84 R0
G3 X288.88 Y151.528 I-7.795 J2.144 E.03264
G3 X289.284 Y157.188 I-49.939 J6.411 E.21143
G3 X289.524 Y164.925 I-145.454 J8.393 E.28836
G1 X165.075 Y164.925 E4.63527
M73 P86 R0
G1 X165.075 Y40.516 E4.63378
M73 P87 R0
G1 E-.8
G1 X165.075 Y165.075 F12000
M73 P88 R0
G1 E.8 F1800
G1 F3000
G1 X289.524 Y165.075 E4.63527
M73 P90 R0
G3 X289.284 Y172.812 I-145.695 J-.655 E.28836
G3 X288.984 Y177.592 I-49.176 J-.686 E.17845
G3 X288.693 Y179.328 I-12.504 J-1.202 E.06558
G3 X179.328 Y288.693 I-123.679 J-14.313 E6.21571
M73 P92 R0
G3 X178.472 Y288.88 I-2.144 J-7.795 E.03264
G3 X172.812 Y289.284 I-6.411 J-49.939 E.21143
G3 X165.075 Y289.524 I-8.393 J-145.454 E.28836
G1 X165.075 Y165.115 E4.63378
M73 P94 R0
G1 E-.8
G1 X165.325 Y289.272 F12000
G1 X176.013 Y289.394
M73 P95 R0
G1 E.8 F1800
;TYPE:Gap infill
;WIDTH:0.150527
G1 F3000
G1 X176.511 Y289.37 E.00437
;WIDTH:0.198096
G1 X177.01 Y289.346 E.0063
;WIDTH:0.245665
G1 X177.508 Y289.322 E.00824
;WIDTH:0.293234
G1 X178.006 Y289.298 E.01017
;WIDTH:0.328339
G1 X178.299 Y289.282 E.00683
;WIDTH:0.372277
G1 X178.524 Y289.269 E.00605
;WIDTH:0.41084
G1 X178.694 Y289.259 E.0051
;WIDTH:0.453503
G1 X178.848 Y289.25 E.00517
;WIDTH:0.492527
G1 X179.003 Y289.24 E.00567
;WIDTH:0.520692
G1 X179.341 Y289.217 E.01319
G1 E-.8
G1 X153.987 Y289.394 F12000
G1 E.8 F1800
;WIDTH:0.102959
G1 F3000
G1 X153.489 Y289.37 E.00244
;WIDTH:0.150528
G1 X152.99 Y289.346 E.00437
;WIDTH:0.198097
G1 X152.492 Y289.322 E.0063
;WIDTH:0.245909
G1 X151.992 Y289.298 E.00829
;WIDTH:0.29407
G1 X151.926 Y289.295 E.00134
;WIDTH:0.301318
G1 X151.701 Y289.282 E.00475
;WIDTH:0.339125
G1 X151.46 Y289.269 E.00582
;WIDTH:0.375452
G1 X151.306 Y289.259 E.00419
;WIDTH:0.414476
G1 X151.152 Y289.25 E.00468
;WIDTH:0.456387
G1 X150.985 Y289.239 E.00563
;WIDTH:0.510122
G1 X150.659 Y289.217 E.01243
G1 E-.8
G1 X150.19 Y289.041 F12000
G1 X126.071 Y283.702
G1 X103.703 Y273.848
G1 X83.042 Y259.282
G1 X66.046 Y241.244
M73 P96 R0
G1 X52.718 Y219.763
G1 X43.996 Y196.036
G1 X40.959 Y179.81
G1 X40.783 Y179.341
G1 E.8 F1800
;WIDTH:0.520692
G1 F3000
G1 X40.76 Y179.003 E.01319
;WIDTH:0.492524
G1 X40.75 Y178.848 E.00567
;WIDTH:0.453501
G1 X40.741 Y178.694 E.00517
;WIDTH:0.410837
G1 X40.731 Y178.524 E.0051
;WIDTH:0.372273
G1 X40.718 Y178.299 E.00605
;WIDTH:0.328338
G1 X40.702 Y178.006 E.00683
;WIDTH:0.293234
G1 X40.678 Y177.508 E.01017
;WIDTH:0.245665
G1 X40.654 Y177.01 E.00824
;WIDTH:0.198096
G1 X40.63 Y176.511 E.0063
;WIDTH:0.150527
G1 X40.606 Y176.013 E.00437
G1 E-.8
G1 X40.606 Y153.987 F12000
G1 E.8 F1800
;WIDTH:0.150528
G1 F3000
G1 X40.63 Y153.489 E.00437
;WIDTH:0.198097
G1 X40.654 Y152.99 E.0063
;WIDTH:0.245666
G1 X40.678 Y152.492 E.00824
;WIDTH:0.293235
G1 X40.702 Y151.994 E.01017
;WIDTH:0.328339
G1 X40.718 Y151.701 E.00683
;WIDTH:0.372276
G1 X40.731 Y151.476 E.00605
;WIDTH:0.41084
G1 X40.741 Y151.306 E.0051
;WIDTH:0.453503
G1 X40.75 Y151.152 E.00517
;WIDTH:0.492526
G1 X40.76 Y150.997 E.00567
;WIDTH:0.52069
G1 X40.783 Y150.659 E.01319
G1 E-.8
M73 P97 R0
G1 X40.959 Y150.19 F12000
G1 X46.298 Y126.071
G1 X56.152 Y103.703
G1 X70.718 Y83.042
G1 X88.756 Y66.046
G1 X110.237 Y52.718
G1 X133.964 Y43.996
G1 X150.19 Y40.959
M73 P98 R0
G1 X150.659 Y40.783
G1 E.8 F1800
;WIDTH:0.510123
G1 F3000
G1 X150.985 Y40.761 E.01243
;WIDTH:0.456389
G1 X151.152 Y40.75 E.00563
;WIDTH:0.414479
G1 X151.306 Y40.741 E.00468
;WIDTH:0.375455
G1 X151.46 Y40.731 E.00419
;WIDTH:0.339125
G1 X151.701 Y40.718 E.00582
;WIDTH:0.301316
G1 X151.926 Y40.705 E.00475
;WIDTH:0.294032
G1 X151.992 Y40.702 E.00135
;WIDTH:0.245871
G1 X152.493 Y40.678 E.00829
;WIDTH:0.198059
G1 X152.991 Y40.654 E.0063
;WIDTH:0.15049
G1 X153.489 Y40.63 E.00437
;WIDTH:0.102921
G1 X153.987 Y40.606 E.00244
G1 E-.8
G1 X176.015 Y40.606 F12000
G1 E.8 F1800
;WIDTH:0.150557
G1 F3000
G1 X176.512 Y40.63 E.00437
;WIDTH:0.19814
G1 X177.01 Y40.654 E.0063
;WIDTH:0.245722
G1 X177.508 Y40.678 E.00824
;WIDTH:0.293304
G1 X178.006 Y40.702 E.01017
;WIDTH:0.328365
G1 X178.299 Y40.718 E.00683
;WIDTH:0.372274
G1 X178.524 Y40.731 E.00604
;WIDTH:0.410837
G1 X178.694 Y40.741 E.0051
;WIDTH:0.4535
G1 X178.848 Y40.75 E.00517
;WIDTH:0.492524
G1 X179.003 Y40.76 E.00567
;WIDTH:0.52069
G1 X179.341 Y40.783 E.01319
G1 E-.8
G1 X179.81 Y40.959 F12000
G1 X203.929 Y46.298
G1 X226.297 Y56.152
G1 X246.958 Y70.718
G1 X263.954 Y88.756
M73 P99 R0
G1 X277.282 Y110.237
G1 X286.004 Y133.964
G1 X289.041 Y150.19
G1 X289.217 Y150.659
G1 E.8 F1800
;WIDTH:0.520692
G1 F3000
G1 X289.24 Y150.997 E.01319
;WIDTH:0.492524
G1 X289.25 Y151.152 E.00567
;WIDTH:0.453501
G1 X289.259 Y151.306 E.00517
;WIDTH:0.410837
G1 X289.269 Y151.476 E.0051
;WIDTH:0.372273
G1 X289.282 Y151.701 E.00605
;WIDTH:0.328338
G1 X289.298 Y151.994 E.00683
;WIDTH:0.293234
G1 X289.322 Y152.492 E.01017
;WIDTH:0.245665
G1 X289.346 Y152.99 E.00824
;WIDTH:0.198096
G1 X289.37 Y153.489 E.0063
;WIDTH:0.150527
G1 X289.394 Y153.987 E.00437
G1 E-.8
G1 X289.394 Y176.015 F12000
G1 E.8 F1800
;WIDTH:0.150554
G1 F3000
G1 X289.37 Y176.512 E.00437
;WIDTH:0.198123
G1 X289.346 Y177.01 E.0063
;WIDTH:0.245692
G1 X289.322 Y177.508 E.00823
;WIDTH:0.29326
G1 X289.298 Y178.006 E.01016
;WIDTH:0.32833
G1 X289.282 Y178.299 E.00684
;WIDTH:0.372276
G1 X289.269 Y178.524 E.00604
;WIDTH:0.410839
G1 X289.259 Y178.694 E.0051
;WIDTH:0.453502
G1 X289.25 Y178.848 E.00517
;WIDTH:0.492526
G1 X289.24 Y179.003 E.00567
;WIDTH:0.52069
G1 X289.217 Y179.341 E.01319
; stop printing object parametric_bed_center_calibration_crosshair.stl id:0 copy 0
G1 E-.8 F3000
EXCLUDE_OBJECT_END NAME=parametric_bed_center_calibration_crosshair.stl_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode 
END_PRINT
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 236.64
; filament used [cm3] = 0.57
; filament used [g] = 0.71
; filament cost = 0.01; total filament used [g] = 0.71
; total filament cost = 0.01
; total layers count = 1
; estimated printing time (normal mode) = 2m 30s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; additional_cooling_fan_speed = 70
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_temperature_difference = 10
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; bottom_shell_layers = 5
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 5
; chamber_temperature = 0
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; curr_bed_type = High Temp Plate
; default_acceleration = 18000
; default_filament_colour = ""
; default_filament_profile = 
; default_jerk = 0
; default_print_profile = 0.16mm Optimal @Bambu Lab X1 Carbon 0.4 nozzle
; deretraction_speed = 60
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = bottom_shell_layers;brim_type;default_acceleration;elefant_foot_compensation;enable_arc_fitting;enable_support;filename_format;gap_infill_speed;initial_layer_acceleration;initial_layer_line_width;inner_wall_line_width;internal_solid_infill_line_width;internal_solid_infill_speed;line_width;only_one_wall_top;outer_wall_acceleration;outer_wall_line_width;outer_wall_speed;reduce_crossing_wall;skirt_loops;sparse_infill_density;sparse_infill_line_width;sparse_infill_speed;support_bottom_z_distance;support_critical_regions_only;support_line_width;support_on_build_plate_only;support_top_z_distance;top_shell_layers;top_surface_acceleration;top_surface_line_width;travel_acceleration;travel_speed;wall_generator;wall_infill_order;wall_loops;xy_hole_compensation;filament_deretraction_speed;filament_retraction_length;filament_retraction_speed;filament_start_gcode;deretraction_speed;extruder_clearance_radius;gcode_flavor;machine_end_gcode;machine_max_acceleration_extruding;machine_max_acceleration_x;machine_max_acceleration_z;machine_max_jerk_e;machine_max_jerk_x;machine_max_jerk_y;machine_max_jerk_z;machine_pause_gcode;machine_start_gcode;print_host;printable_area;retract_length_toolchange;retract_when_changing_layer;retraction_length;wipe
; draft_shield = disabled
; elefant_foot_compensation = 0.1
; enable_arc_fitting = 1
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 1
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = 1
; exclude_object = 1
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 45
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #00AE42
; filament_cost = 20
; filament_density = 1.24
; filament_deretraction_speed = 30
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.98
; filament_ids = GFL99
; filament_is_support = 0
; filament_max_volumetric_speed = 12
; filament_minimal_purge_on_wipe_tower = 15
; filament_retraction_length = 0.8
; filament_retraction_speed = 50
; filament_settings_id = PLA
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n{if nozzle_diameter[0] == 0.2}\n     PRESSURE_ADVANCE_SELECT Nozzle=0.2 FILAMENT=PLA\n{ else }\n    PRESSURE_ADVANCE_SELECT FILAMENT=PLA\n{ endif }"
; filament_type = PLA
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.55
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_infill_speed = 200
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @Tronxy";"Tronxy Generic PLA";"Tronxy X5SA 400 0.4 nozzle"
; initial_layer_acceleration = 1000
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 125%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 10000
; inner_wall_jerk = 9
; inner_wall_line_width = 0
; inner_wall_speed = 200
; interface_shells = 0
; internal_bridge_speed = 150%
; internal_bridge_support_thickness = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 140%
; internal_solid_infill_pattern = zig-zag
; internal_solid_infill_speed = 180
; ironing_flow = 10%
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 115%
; machine_end_gcode = END_PRINT
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 6000
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 20000
; machine_max_acceleration_y = 10000
; machine_max_acceleration_z = 1000
; machine_max_jerk_e = 2.5
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 0.2
; machine_max_speed_e = 60
; machine_max_speed_x = 500
; machine_max_speed_y = 500
; machine_max_speed_z = 10
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = PAUSE
; machine_start_gcode = START_PRINT T_BED=[first_layer_bed_temperature] T_EXTRUDER=[first_layer_temperature]
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_travel_detour_distance = 0
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 230
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; outer_wall_acceleration = 12000
; outer_wall_jerk = 9
; outer_wall_line_width = 100%
; outer_wall_speed = 180
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_speed_classic = 1
; post_process = 
; precise_outer_wall = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Tronxy X5SA 400 0.4 nozzle"
; print_flow_ratio = 1
; print_host = 192.168.6.5:7126
; print_host_webui = 
; print_sequence = by layer
; print_settings_id = 0.20mm @Tronxy
; printable_area = 0x0,330x0,330x330,0x330
; printable_height = 400
; printer_model = Tronxy X5SA 400 Marlin Firmware
; printer_settings_id = TronXY X5SA
; printer_technology = FFF
; printer_variant = 0.4
; printhost_apikey = 
; printhost_authorization_type = key
; printhost_cafile = 
; printhost_password = 
; printhost_port = 
; printhost_ssl_ignore_revoke = 0
; printhost_user = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 1
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 0
; retraction_length = 0.5
; retraction_minimum_travel = 2
; retraction_speed = 60
; role_based_wipe_speed = 1
; scan_first_layer = 0
; seam_gap = 10%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 2
; skirt_speed = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 10
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 25%
; sparse_infill_filament = 1
; sparse_infill_line_width = 160%
; sparse_infill_pattern = grid
; sparse_infill_speed = 250
; spiral_mode = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.23
; support_critical_regions_only = 1
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_pattern = rectilinear
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0
; support_material_interface_fan_speed = -1
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 1
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.23
; support_type = normal(auto)
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thumbnails = 300x300
; timelapse_type = 0
; top_shell_layers = 5
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 1500
; top_surface_jerk = 9
; top_surface_line_width = 100%
; top_surface_pattern = monotonic
; top_surface_speed = 100
; travel_acceleration = 15000
; travel_jerk = 12
; travel_speed = 200
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_diameter = 5
; tree_support_branch_distance = 5
; tree_support_brim_width = 3
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_infill_order = outer wall/inner wall/infill
; wall_loops = 4
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 155.000
; wipe_tower_y = 220.000
; xy_contour_compensation = 0
; xy_hole_compensation = 0.075
; z_hop = 0
; z_hop_types = Normal Lift
; first_layer_bed_temperature = 60
; bed_shape = 0x0,330x0,330x330,0x330
; first_layer_temperature = 220
; first_layer_height = 0.200
; CONFIG_BLOCK_END


